import { RPG_ZONE_BY_ID, type RpgZoneId } from './rpg-zone-definitions';

/**
 * wave-definitions.ts — Data definitions for RPG wave-based enemy spawning.
 *
 * Waves are pre-defined for the first several waves (1–25); higher waves are
 * generated procedurally so new wave data can be added without touching renderer
 * logic.  New enemy types are supported by registering a new `enemyTypeId` and
 * handling it in the RPG renderer.
 *
 * ── Standard enemies (difficulty order) ──────────────────────────
 *  'laser'      — red dash-striker, low HP,               first appears wave 1
 *  'quartz'     — white crystal orbiter,                  first appears wave 1
 *  'sapphire'   — blue shielded missile-launcher,         first appears wave 6
 *  'emerald'    — green blink-striker, teleports to player, wave 9
 *  'ruby'       — fast red patroller with rapid bolts,    first appears wave 10
 *  'amber'      — orange fan-gunner, fires 3 homing shards, wave 12
 *  'void'       — purple slow bruiser, constant pursuit,  first appears wave 15
 *  'sunstone'   — orange orbiter with area pulse,         first appears wave 20
 *  'citrine'    — yellow fast patrol + homing bolts,      first appears wave 30
 *  'iolite'     — indigo tanky beam-blaster,              first appears wave 40
 *  'amethyst'   — purple crystal-shielder ring-burst,     first appears wave 50
 *  'diamond'    — phase-shifting shard-shooter,           first appears wave 60
 *  'nullstone'  — gravity well with void tendrils,        first appears wave 70
 *  'fracteryl'  — fractal recursive shard storm,          first appears wave 74
 *  'eigenstein' — sweeping math beam,                     first appears wave 85
 *
 * ── Elite enemies ─────────────────────────────────────────────────
 *  'elite_quartz'    — crown quartz, double spike bursts,   wave 2+
 *  'elite_ruby'      — blazing crimson hunter,              wave 5+
 *  'elite_sunstone'  — searing close-range sun,             wave 10+
 *  'elite_citrine'   — double bolt barrage,                 wave 15+
 *  'elite_iolite'    — gravity-well beam colossus,          wave 33+
 *  'elite_amethyst'  — regen shield ring-burst fortress,    wave 42+
 *  'elite_diamond'   — nine-star shard burst,               wave 52+
 *  'elite_nullstone' — Event Horizon singularity,           wave 63+
 *
 * ── Aliven particle swarms ────────────────────────────────────────
 * Aliven variants are exclusive to the Impetus zone (see _getImpetusWaveDefinition);
 * they are never used by Euhedral's hand-authored or procedural waves.
 *  'aliven_spark_cluster'   — 8-mote spitter swarm,         wave 2+
 *  'aliven_quartz_ghost'    — phasing 10-particle swarm,    wave 4+
 *  'aliven_shard_bloom'     — 10-particle dasher swarm,     wave 5+
 *  'aliven_pulse_swarm'     — 10-pulser shockwave swarm,    wave 8+
 *  'aliven_ember_ring'      — 10-ember trail swarm,         wave 12+
 *  'aliven_void_splinters'  — 12-splitter swarm,            wave 18+
 *  'aliven_healer_nodes'    — 9-particle healer swarm,      wave 22+
 *  'aliven_orbit_bloom'     — 12-orbiter swarm,             wave 28+
 *  'aliven_iolite_prism'    — 14-pulser dense cluster,      wave 38+
 *  'aliven_fracteryl_storm' — 18-splitter fractal cascade,  wave 65+
 *
 * ── Procedurally animated enemies ────────────────────────────────
 * These are generated by the procedural generator only (waves 26+).
 * Pre-defined waves 1–25 do not include them.
 *  'proc_dustwisp'      — drifting mote with sparkle orbit, wave 26+
 *  'proc_ribbonworm'    — segmented worm, wave 26+
 *  'proc_lanternmoth'   — flapping wing moth, wave 26+
 *  'proc_eyestalk'      — swaying eye on a stalk, wave 26+
 *  'proc_jellyfish'     — pulsing bell jellyfish, wave 26+
 *  'proc_clothghost'    — fluttering cloth sheet, wave 26+
 *  'proc_plantturret'   — root-anchored spore shooter, wave 26+
 *  'proc_gearinsect'    — spinning gear bug, wave 26+
 *  'proc_spidercrawler' — 8-legged crawler, wave 26+
 *  'proc_moteswarm'     — orbiting mote cluster, wave 26+
 *  'proc_shadowhand'    — grasping dark hand, wave 32+
 *  'proc_sandfish'      — lunging dune fish, wave 34+
 *  'proc_quartzfish'    — shielded crystal fish, wave 38+
 *  'proc_rubyfish'      — windup dash fish, wave 42+
 *  'proc_sunstonefish'  — mine-laying ember fish, wave 46+
 *  'proc_emeraldfish'   — splitting emerald fish, wave 50+
 *  'proc_sapphirefish'  — bolt-firing blue fish, wave 54+
 *  'proc_amethystfish'  — teleporting decoy fish, wave 58+
 *  'proc_diamondfish'   — armored prismatic fish, wave 62+
 *
 * ── Boss ─────────────────────────────────────────────────────────
 *  'boss' — appears every 100 waves; escalating difficulty
 */

// ─── Types ────────────────────────────────────────────────────────

/** A single spawn group within a wave. */
export interface WaveSpawn {
  /** Registry key used to instantiate the correct enemy variant. */
  enemyTypeId: string;
  /** How many enemies in this group. */
  count: number;
  /** Milliseconds between each successive spawn in the group. */
  spawnDelay: number;
}

/** Full specification for one wave. */
export interface WaveDefinition {
  waveNumber: number;
  spawns: WaveSpawn[];
  isBossWave?: boolean;
}

// ─── Pre-defined waves ────────────────────────────────────────────

/** Hand-authored wave definitions for early progression. */
export const WAVE_DEFINITIONS: WaveDefinition[] = [
  {
    waveNumber: 1,
    spawns: [
      { enemyTypeId: 'laser',  count: 1, spawnDelay:   0 },
      { enemyTypeId: 'quartz', count: 1, spawnDelay: 500 },
    ],
  },
  {
    waveNumber: 2,
    spawns: [
      { enemyTypeId: 'laser',                count: 2, spawnDelay:  800 },
      { enemyTypeId: 'quartz',               count: 1, spawnDelay:  600 },
    ],
  },
  {
    waveNumber: 3,
    spawns: [
      { enemyTypeId: 'laser',                count: 2, spawnDelay:  600 },
      { enemyTypeId: 'quartz',               count: 2, spawnDelay:  700 },
    ],
  },
  {
    waveNumber: 4,
    spawns: [
      { enemyTypeId: 'laser',                count: 3, spawnDelay:  700 },
      { enemyTypeId: 'quartz',               count: 2, spawnDelay:  600 },
    ],
  },
  // Wave 5: no boss before wave 100
  {
    waveNumber: 5,
    spawns: [
      { enemyTypeId: 'laser',                count: 2, spawnDelay:  600 },
      { enemyTypeId: 'quartz',               count: 1, spawnDelay:  700 },
    ],
  },
  {
    waveNumber: 6,
    spawns: [
      { enemyTypeId: 'laser',                count: 2, spawnDelay:  700 },
      { enemyTypeId: 'quartz',               count: 2, spawnDelay:  600 },
      { enemyTypeId: 'sapphire',             count: 1, spawnDelay:  900 },
    ],
  },
  {
    waveNumber: 7,
    spawns: [
      { enemyTypeId: 'laser',                count: 3, spawnDelay:  600 },
      { enemyTypeId: 'quartz',               count: 2, spawnDelay:  550 },
      { enemyTypeId: 'sapphire',             count: 1, spawnDelay:  900 },
    ],
  },
  {
    waveNumber: 8,
    spawns: [
      { enemyTypeId: 'laser',                count: 3, spawnDelay:  600 },
      { enemyTypeId: 'quartz',               count: 2, spawnDelay:  500 },
      { enemyTypeId: 'sapphire',             count: 2, spawnDelay: 1200 },
    ],
  },
  {
    waveNumber: 9,
    spawns: [
      { enemyTypeId: 'laser',                count: 3, spawnDelay:  500 },
      { enemyTypeId: 'quartz',               count: 2, spawnDelay:  500 },
      { enemyTypeId: 'sapphire',             count: 2, spawnDelay: 1100 },
      { enemyTypeId: 'emerald',              count: 1, spawnDelay: 1300 },
    ],
  },
  // Wave 10: no boss before wave 100
  {
    waveNumber: 10,
    spawns: [
      { enemyTypeId: 'laser',                     count: 3, spawnDelay:  500 },
      { enemyTypeId: 'quartz',                    count: 2, spawnDelay:  480 },
      { enemyTypeId: 'sapphire',                  count: 1, spawnDelay: 1000 },
    ],
  },
  {
    waveNumber: 11,
    spawns: [
      { enemyTypeId: 'laser',                count: 4, spawnDelay:  500 },
      { enemyTypeId: 'quartz',               count: 2, spawnDelay:  460 },
      { enemyTypeId: 'sapphire',             count: 2, spawnDelay: 1000 },
      { enemyTypeId: 'emerald',              count: 2, spawnDelay: 1100 },
    ],
  },
  {
    waveNumber: 12,
    spawns: [
      { enemyTypeId: 'laser',                count: 4, spawnDelay:  500 },
      { enemyTypeId: 'quartz',               count: 3, spawnDelay:  450 },
      { enemyTypeId: 'sapphire',             count: 2, spawnDelay: 1000 },
      { enemyTypeId: 'emerald',              count: 2, spawnDelay: 1100 },
      { enemyTypeId: 'amber',               count: 1, spawnDelay: 1400 },
    ],
  },
  {
    waveNumber: 13,
    spawns: [
      { enemyTypeId: 'laser',                count: 4, spawnDelay:  480 },
      { enemyTypeId: 'quartz',               count: 3, spawnDelay:  430 },
      { enemyTypeId: 'sapphire',             count: 2, spawnDelay:  950 },
      { enemyTypeId: 'emerald',              count: 2, spawnDelay: 1000 },
      { enemyTypeId: 'amber',               count: 1, spawnDelay: 1300 },
    ],
  },
  {
    waveNumber: 14,
    spawns: [
      { enemyTypeId: 'laser',                count: 4, spawnDelay:  460 },
      { enemyTypeId: 'quartz',               count: 3, spawnDelay:  420 },
      { enemyTypeId: 'sapphire',             count: 3, spawnDelay:  900 },
      { enemyTypeId: 'emerald',              count: 2, spawnDelay:  950 },
      { enemyTypeId: 'amber',               count: 2, spawnDelay: 1200 },
    ],
  },
  // Wave 15: no boss before wave 100
  {
    waveNumber: 15,
    spawns: [
      { enemyTypeId: 'laser',                count: 4, spawnDelay:  450 },
      { enemyTypeId: 'quartz',               count: 2, spawnDelay:  420 },
      { enemyTypeId: 'emerald',              count: 2, spawnDelay:  900 },
      { enemyTypeId: 'amber',               count: 1, spawnDelay: 1100 },
    ],
  },
  {
    waveNumber: 16,
    spawns: [
      { enemyTypeId: 'laser',                count: 4, spawnDelay:  430 },
      { enemyTypeId: 'quartz',               count: 3, spawnDelay:  400 },
      { enemyTypeId: 'sapphire',             count: 3, spawnDelay:  900 },
      { enemyTypeId: 'emerald',              count: 2, spawnDelay:  880 },
      { enemyTypeId: 'amber',               count: 2, spawnDelay: 1100 },
      { enemyTypeId: 'void',                count: 1, spawnDelay: 1700 },
    ],
  },
  {
    waveNumber: 17,
    spawns: [
      { enemyTypeId: 'laser',                count: 5, spawnDelay:  420 },
      { enemyTypeId: 'quartz',               count: 3, spawnDelay:  400 },
      { enemyTypeId: 'sapphire',             count: 3, spawnDelay:  880 },
      { enemyTypeId: 'emerald',              count: 3, spawnDelay:  860 },
      { enemyTypeId: 'amber',               count: 2, spawnDelay: 1100 },
      { enemyTypeId: 'void',                count: 1, spawnDelay: 1600 },
    ],
  },
  {
    waveNumber: 18,
    spawns: [
      { enemyTypeId: 'laser',                count: 5, spawnDelay:  400 },
      { enemyTypeId: 'quartz',               count: 3, spawnDelay:  380 },
      { enemyTypeId: 'sapphire',             count: 3, spawnDelay:  860 },
      { enemyTypeId: 'emerald',              count: 3, spawnDelay:  840 },
      { enemyTypeId: 'amber',               count: 2, spawnDelay: 1050 },
      { enemyTypeId: 'void',                count: 2, spawnDelay: 1600 },
    ],
  },
  {
    waveNumber: 19,
    spawns: [
      { enemyTypeId: 'laser',                count: 5, spawnDelay:  380 },
      { enemyTypeId: 'quartz',               count: 3, spawnDelay:  360 },
      { enemyTypeId: 'sapphire',             count: 3, spawnDelay:  840 },
      { enemyTypeId: 'emerald',              count: 3, spawnDelay:  820 },
      { enemyTypeId: 'amber',               count: 3, spawnDelay: 1000 },
      { enemyTypeId: 'void',                count: 2, spawnDelay: 1500 },
    ],
  },
  // Wave 20: no boss before wave 100
  {
    waveNumber: 20,
    spawns: [
      { enemyTypeId: 'laser',                     count: 4, spawnDelay:  380 },
      { enemyTypeId: 'quartz',                    count: 3, spawnDelay:  360 },
      { enemyTypeId: 'sapphire',                  count: 2, spawnDelay:  820 },
      { enemyTypeId: 'amber',                     count: 2, spawnDelay:  950 },
      { enemyTypeId: 'void',                      count: 1, spawnDelay: 1400 },
    ],
  },
  {
    waveNumber: 21,
    spawns: [
      { enemyTypeId: 'laser',                count: 6, spawnDelay:  360 },
      { enemyTypeId: 'quartz',               count: 3, spawnDelay:  340 },
      { enemyTypeId: 'sapphire',             count: 4, spawnDelay:  820 },
      { enemyTypeId: 'emerald',              count: 4, spawnDelay:  800 },
      { enemyTypeId: 'amber',               count: 3, spawnDelay:  950 },
      { enemyTypeId: 'void',                count: 2, spawnDelay: 1400 },
    ],
  },
  {
    waveNumber: 22,
    spawns: [
      { enemyTypeId: 'laser',                count: 6, spawnDelay:  340 },
      { enemyTypeId: 'quartz',               count: 4, spawnDelay:  320 },
      { enemyTypeId: 'sapphire',             count: 4, spawnDelay:  800 },
      { enemyTypeId: 'emerald',              count: 4, spawnDelay:  780 },
      { enemyTypeId: 'amber',               count: 3, spawnDelay:  920 },
      { enemyTypeId: 'void',                count: 2, spawnDelay: 1350 },
      { enemyTypeId: 'ruby',                count: 2, spawnDelay:  900 },
    ],
  },
  {
    waveNumber: 23,
    spawns: [
      { enemyTypeId: 'laser',                count: 6, spawnDelay:  320 },
      { enemyTypeId: 'quartz',               count: 4, spawnDelay:  300 },
      { enemyTypeId: 'sapphire',             count: 4, spawnDelay:  780 },
      { enemyTypeId: 'emerald',              count: 4, spawnDelay:  760 },
      { enemyTypeId: 'amber',               count: 3, spawnDelay:  900 },
      { enemyTypeId: 'void',                count: 3, spawnDelay: 1300 },
      { enemyTypeId: 'ruby',                count: 3, spawnDelay:  880 },
    ],
  },
  {
    waveNumber: 24,
    spawns: [
      { enemyTypeId: 'laser',                count: 7, spawnDelay:  300 },
      { enemyTypeId: 'quartz',               count: 4, spawnDelay:  280 },
      { enemyTypeId: 'sapphire',             count: 4, spawnDelay:  760 },
      { enemyTypeId: 'emerald',              count: 5, spawnDelay:  740 },
      { enemyTypeId: 'amber',               count: 4, spawnDelay:  880 },
      { enemyTypeId: 'void',                count: 3, spawnDelay: 1250 },
      { enemyTypeId: 'ruby',                count: 3, spawnDelay:  860 },
    ],
  },
  // Wave 25: no boss before wave 100
  {
    waveNumber: 25,
    spawns: [
      { enemyTypeId: 'laser',                count: 5, spawnDelay:  300 },
      { enemyTypeId: 'quartz',               count: 3, spawnDelay:  280 },
      { enemyTypeId: 'emerald',              count: 3, spawnDelay:  740 },
      { enemyTypeId: 'amber',               count: 2, spawnDelay:  880 },
      { enemyTypeId: 'void',                count: 2, spawnDelay: 1250 },
      { enemyTypeId: 'ruby',                count: 2, spawnDelay:  860 },
    ],
  },
];

// ─── Procedural generator ─────────────────────────────────────────

/**
 * Returns the WaveDefinition for the given wave number.
 * Waves beyond WAVE_DEFINITIONS are generated procedurally, scaling
 * enemy count and tightening spawn delay as the wave number grows.
 * Boss waves begin at wave 100 and repeat every 100 waves.
 */
export function getWaveDefinition(waveNumber: number): WaveDefinition {
  const predefined = WAVE_DEFINITIONS.find(w => w.waveNumber === waveNumber);
  if (predefined) return predefined;

  // Wave 50 — Sand Warden tutorial boss (minimal escort, very slow)
  if (waveNumber === 50) {
    return {
      waveNumber,
      isBossWave: true,
      spawns: [
        { enemyTypeId: 'laser',  count: 2, spawnDelay: 600 },
        { enemyTypeId: 'quartz', count: 1, spawnDelay: 800 },
        { enemyTypeId: 'boss',   count: 1, spawnDelay: 2500 },
      ],
    };
  }

  // Boss wave every 100 waves — boss with a small escort
  if (waveNumber % 100 === 0) {
    const delay = Math.max(130, 600 - waveNumber * 18);
    const escort: WaveSpawn[] = [];
    const laserCount  = Math.min(2 + Math.floor(waveNumber * 0.15), 6);
    const quartzCount = Math.min(1 + Math.floor(waveNumber * 0.1),  4);
    escort.push({ enemyTypeId: 'laser',  count: laserCount,  spawnDelay: delay });
    escort.push({ enemyTypeId: 'quartz', count: quartzCount, spawnDelay: delay });
    if (waveNumber >= 30) escort.push({ enemyTypeId: 'void',      count: 1, spawnDelay: delay + 900 });
    if (waveNumber >= 40) escort.push({ enemyTypeId: 'diamond',   count: 1, spawnDelay: delay + 1100 });
    if (waveNumber >= 60) escort.push({ enemyTypeId: 'nullstone', count: 1, spawnDelay: delay + 1400 });
    escort.push({ enemyTypeId: 'boss', count: 1, spawnDelay: delay + 2500 });
    return { waveNumber, isBossWave: true, spawns: escort };
  }

  // Procedural: count grows slowly; delay tightens as waves increase.
  // Only Euhedral-native enemy types spawn here — proc enemies (ribbonworm,
  // jellyfish, fish, etc.) belong to Verdure / Caustics / Impetus and must
  // never appear in Euhedral waves.
  const laserCount     = Math.min(2 + Math.floor(waveNumber * 0.4), 9);
  const quartzCount    = Math.min(2 + Math.floor(waveNumber * 0.35), 8);
  const rubyCount      = waveNumber >= 5   ? Math.min(1 + Math.floor((waveNumber -  4) * 0.25), 6) : 0;
  const sunstoneCount  = waveNumber >= 10  ? Math.min(1 + Math.floor((waveNumber -  9) * 0.22), 5) : 0;
  const citrineCount   = waveNumber >= 15  ? Math.min(1 + Math.floor((waveNumber - 14) * 0.18), 5) : 0;
  const amberCount     = waveNumber >= 18  ? Math.min(1 + Math.floor((waveNumber - 17) * 0.15), 4) : 0;
  const emeraldCount   = waveNumber >= 21  ? Math.min(1 + Math.floor((waveNumber - 20) * 0.22), 5) : 0;
  const voidCount      = waveNumber >= 24  ? Math.min(1 + Math.floor((waveNumber - 23) * 0.12), 3) : 0;
  const sapphireCount  = waveNumber >= 27  ? Math.min(1 + Math.floor((waveNumber - 26) * 0.20), 5) : 0;
  const ioliteCount    = waveNumber >= 33  ? Math.min(1 + Math.floor((waveNumber - 32) * 0.14), 4) : 0;
  const amethystCount  = waveNumber >= 42  ? Math.min(1 + Math.floor((waveNumber - 41) * 0.11), 3) : 0;
  const diamondCount   = waveNumber >= 52  ? Math.min(1 + Math.floor((waveNumber - 51) * 0.08), 3) : 0;
  const nullstoneCount = waveNumber >= 63  ? Math.min(1 + Math.floor((waveNumber - 62) * 0.05), 2) : 0;
  const fracterylCount = waveNumber >= 74  ? Math.min(1 + Math.floor((waveNumber - 73) * 0.04), 2) : 0;
  const eigensteinCount= waveNumber >= 85  ? Math.min(1 + Math.floor((waveNumber - 84) * 0.03), 2) : 0;
  // Stardust enemy: rare prismatic particle cloud + laser bouncer (Euhedral-native)
  const stardustCount  = waveNumber >= 35  ? Math.floor((waveNumber - 34) * 0.008 + Math.random() * 0.5) : 0;
  const delay = Math.max(130, 600 - waveNumber * 18);
  const spawns: WaveSpawn[] = [
    { enemyTypeId: 'laser',  count: laserCount,  spawnDelay: delay },
    { enemyTypeId: 'quartz', count: quartzCount, spawnDelay: delay },
  ];
  if (waveNumber >= 5)   spawns.push({ enemyTypeId: 'ruby',       count: rubyCount,       spawnDelay: delay + 300 });
  if (waveNumber >= 10)  spawns.push({ enemyTypeId: 'sunstone',   count: sunstoneCount,   spawnDelay: delay + 400 });
  if (waveNumber >= 15)  spawns.push({ enemyTypeId: 'citrine',    count: citrineCount,    spawnDelay: delay + 500 });
  if (waveNumber >= 18)  spawns.push({ enemyTypeId: 'amber',      count: amberCount,      spawnDelay: delay + 600 });
  if (waveNumber >= 21)  spawns.push({ enemyTypeId: 'emerald',    count: emeraldCount,    spawnDelay: delay + 350 });
  if (waveNumber >= 24)  spawns.push({ enemyTypeId: 'void',       count: voidCount,       spawnDelay: delay + 900 });
  if (waveNumber >= 27)  spawns.push({ enemyTypeId: 'sapphire',   count: sapphireCount,   spawnDelay: delay + 400 });
  if (waveNumber >= 33)  spawns.push({ enemyTypeId: 'iolite',     count: ioliteCount,     spawnDelay: delay + 800 });
  if (waveNumber >= 42)  spawns.push({ enemyTypeId: 'amethyst',   count: amethystCount,   spawnDelay: delay + 1000 });
  if (waveNumber >= 52)  spawns.push({ enemyTypeId: 'diamond',    count: diamondCount,    spawnDelay: delay + 1200 });
  if (waveNumber >= 63)  spawns.push({ enemyTypeId: 'nullstone',  count: nullstoneCount,  spawnDelay: delay + 1500 });
  if (waveNumber >= 74)  spawns.push({ enemyTypeId: 'fracteryl',  count: fracterylCount,  spawnDelay: delay + 1700 });
  if (waveNumber >= 85)  spawns.push({ enemyTypeId: 'eigenstein', count: eigensteinCount, spawnDelay: delay + 2000 });
  if (waveNumber >= 35 && stardustCount > 0) spawns.push({ enemyTypeId: 'stardust', count: stardustCount, spawnDelay: delay + 2200 });

  // Elite spawns: one per wave at the correct tier unlock threshold, then sparse thereafter.
  // Each elite spawns well after the main pack to give it a dramatic entrance.
  // Frequency: approximately one elite per 4–6 waves (seeded by wave number for consistency).
  const eliteSpawnRoll = (waveNumber * 7919 + 3571) % 17; // 0-16; threshold ≤ 3 = ~24% chance
  if (eliteSpawnRoll <= 3) {
    // Pick the highest tier available for this wave
    let eliteTier: string | null = null;
    if (waveNumber >= 63)       eliteTier = 'elite_nullstone';
    else if (waveNumber >= 52)  eliteTier = 'elite_diamond';
    else if (waveNumber >= 42)  eliteTier = 'elite_amethyst';
    else if (waveNumber >= 33)  eliteTier = 'elite_iolite';
    else if (waveNumber >= 15)  eliteTier = 'elite_citrine';
    else if (waveNumber >= 10)  eliteTier = 'elite_sunstone';
    else if (waveNumber >= 5)   eliteTier = 'elite_ruby';
    else if (waveNumber >= 2)   eliteTier = 'elite_quartz';
    if (eliteTier !== null) {
      spawns.push({ enemyTypeId: eliteTier, count: 1, spawnDelay: delay + 2500 });
    }
  }

  return { waveNumber, spawns };
}

// ─── Enemy type ID sets (for catalog coverage validation) ─────────

/**
 * All procedural creature IDs used by the wave generator.
 * Exported so test code can validate catalog coverage without
 * re-parsing the generator body.
 */
export const PROCEDURAL_WAVE_ENEMY_IDS: readonly string[] = [
  'proc_dustwisp',
  'proc_ribbonworm',
  'proc_lanternmoth',
  'proc_eyestalk',
  'proc_jellyfish',
  'proc_clothghost',
  'proc_plantturret',
  'proc_gearinsect',
  'proc_spidercrawler',
  'proc_moteswarm',
  'proc_shadowhand',
  'proc_sandfish',
  'proc_quartzfish',
  'proc_rubyfish',
  'proc_sunstonefish',
  'proc_emeraldfish',
  'proc_sapphirefish',
  'proc_amethystfish',
  'proc_diamondfish',
];

/**
 * All standard enemy IDs used by hand-authored and procedural wave definitions
 * (excludes bosses and elite variants, which have separate handling).
 */
export const STANDARD_WAVE_ENEMY_IDS: readonly string[] = [
  'laser', 'quartz', 'sapphire', 'emerald', 'ruby', 'amber', 'void',
  'sunstone', 'citrine', 'iolite', 'amethyst', 'diamond', 'nullstone',
  'fracteryl', 'eigenstein',
];

/**
 * All elite enemy IDs used by the wave generator.
 */
export const ELITE_WAVE_ENEMY_IDS: readonly string[] = [
  'elite_quartz', 'elite_ruby', 'elite_sunstone', 'elite_citrine',
  'elite_iolite', 'elite_amethyst', 'elite_diamond', 'elite_nullstone',
];

// ─── Zone-aware wave generation ────────────────────────────────────

// ─── Impetus zone wave generator ──────────────────────────────────────────────

/**
 * Aliven types in unlock order for the Impetus zone, matching the difficulty
 * progression used in the hand-authored Euhedral waves.
 */
const _IMPETUS_ALIVEN_ORDER = [
  'aliven_spark_cluster',
  'aliven_quartz_ghost',
  'aliven_shard_bloom',
  'aliven_pulse_swarm',
  'aliven_ember_ring',
  'aliven_void_splinters',
  'aliven_healer_nodes',
  'aliven_orbit_bloom',
  'aliven_iolite_prism',
  'aliven_fracteryl_storm',
] as const;

/**
 * Returns a curated WaveDefinition for the Impetus zone.
 *
 * Hard cap: at most 2 normal aliven groups per wave (the two most-recently
 * unlocked types) plus 1 elite group on every 10th wave.  This bounds particle-
 * life pair-check cost regardless of wave number, while still surfacing new
 * mechanics as the player progresses.  Proc enemies scale normally.
 */
function _getImpetusWaveDefinition(waveNumber: number): WaveDefinition {
  const delay = Math.max(130, 600 - waveNumber * 18);
  const spawns: WaveSpawn[] = [];

  // Unlock one new aliven type every 3 waves, capped at the full roster.
  const unlockedCount = Math.min(
    Math.ceil(waveNumber / 3),
    _IMPETUS_ALIVEN_ORDER.length,
  );

  // Normal group 1 — most recently unlocked type.
  const g1 = _IMPETUS_ALIVEN_ORDER[unlockedCount - 1];
  spawns.push({ enemyTypeId: g1, count: 1, spawnDelay: delay + 400 });

  // Normal group 2 — second-most recently unlocked type (if available).
  if (unlockedCount >= 2) {
    const g2 = _IMPETUS_ALIVEN_ORDER[unlockedCount - 2];
    spawns.push({ enemyTypeId: g2, count: 1, spawnDelay: delay + 900 });
  }

  // Elite aliven every 10th wave — one group of the highest-tier unlocked type.
  // Elite groups retain player-seeking behavior that normal groups do not have.
  if (waveNumber % 10 === 0 && unlockedCount >= 1) {
    const eliteBase = _IMPETUS_ALIVEN_ORDER[unlockedCount - 1];
    // Derives e.g. 'aliven_elite_spark_cluster' from 'aliven_spark_cluster'.
    const eliteId = eliteBase.replace('aliven_', 'aliven_elite_');
    spawns.push({ enemyTypeId: eliteId, count: 1, spawnDelay: delay + 1600 });
  }

  // Proc enemies native to Impetus — scale normally.
  const procCount = Math.min(1 + Math.floor(waveNumber * 0.2), 4);
  if (waveNumber >= 5)  spawns.push({ enemyTypeId: 'proc_dustwisp',   count: procCount,              spawnDelay: delay + 200 });
  if (waveNumber >= 26) spawns.push({ enemyTypeId: 'proc_moteswarm',  count: Math.min(procCount, 3), spawnDelay: delay + 500 });
  if (waveNumber >= 32) spawns.push({ enemyTypeId: 'proc_shadowhand', count: Math.min(procCount, 2), spawnDelay: delay + 700 });

  return { waveNumber, spawns };
}

// ─── Zone-aware wave generation ────────────────────────────────────────────────

/**
 * Tracks which empty-pool zones have already emitted a dev warning this session,
 * to avoid spamming the console.
 */
const _warnedEmptyZones = new Set<string>();

/**
 * Returns a WaveDefinition for the given wave number, filtered to the given
 * zone's enemy pool.
 *
 *  - 'euhedral':       returns the standard wave definition unchanged.
 *  - Other zones:      generates a zone-specific wave using only the enemies in
 *                      that zone's pool, with wave-number-based scaling.
 *  - 'horizon' (empty pool): emits a dev-mode warning (once per session) and
 *                      returns no spawns.  The wave will complete immediately;
 *                      this is the intended safe fallback until Horizon enemies
 *                      are assigned.
 */
export function getZoneWaveDefinition(waveNumber: number, zoneId: RpgZoneId): WaveDefinition {
  if (zoneId === 'euhedral') {
    return getWaveDefinition(waveNumber);
  }
  if (zoneId === 'impetus') {
    return _getImpetusWaveDefinition(waveNumber);
  }

  if (zoneId === 'verdure' && waveNumber > 0 && waveNumber % 10 === 0) {
    const tier = Math.max(1, Math.floor(waveNumber / 10));
    const baseCount = Math.min(2 + tier, 7);
    const fissileCount = Math.min(1 + Math.floor(tier / 2), 4);
    const refractorCount = Math.min(1 + Math.floor((tier + 1) / 2), 4);
    const baseDelay = Math.max(120, 520 - tier * 26);
    return {
      waveNumber,
      spawns: [
        { enemyTypeId: 'verdure_polyomino', count: baseCount, spawnDelay: baseDelay },
        { enemyTypeId: 'verdure_polyomino_fissile', count: fissileCount, spawnDelay: baseDelay + 180 },
        { enemyTypeId: 'verdure_polyomino_refractor', count: refractorCount, spawnDelay: baseDelay + 340 },
      ],
    };
  }

  const zoneDef = RPG_ZONE_BY_ID.get(zoneId);
  if (!zoneDef || zoneDef.enemyIds.length === 0) {
    if (!_warnedEmptyZones.has(zoneId)) {
      console.warn(
        `[RPG] Zone '${zoneId}' has no enemies assigned — ` +
        `waves will be empty until enemies are added to its enemyIds list.`,
      );
      _warnedEmptyZones.add(zoneId);
    }
    return { waveNumber, spawns: [] };
  }

  // Progressively introduce enemy types as wave number increases.
  // Wave W unlocks the first ceil(W / 3) types from the zone's ordered list.
  const totalTypes = zoneDef.enemyIds.length;
  const unlockedCount = Math.min(Math.ceil(waveNumber / 3), totalTypes);
  const unlockedIds = zoneDef.enemyIds.slice(0, unlockedCount);

  // Scale count per type and spawn delay with wave number.
  const count = Math.min(1 + Math.floor(waveNumber * 0.3), 6);
  const delay = Math.max(130, 600 - waveNumber * 18);

  const spawns: WaveSpawn[] = unlockedIds.map((enemyTypeId, index) => ({
    enemyTypeId,
    count,
    spawnDelay: delay + index * 200,
  }));

  return { waveNumber, spawns };
}

// ─── Zone-spawn helper ──────────────────────────────────────────────────────

/**
 * Returns the canonical set of enemy type IDs that may spawn in the given zone.
 *
 * For Euhedral this is derived from STANDARD_WAVE_ENEMY_IDS + ELITE_WAVE_ENEMY_IDS +
 * stardust + boss.  For all other zones it is their `enemyIds` list from
 * rpg-zone-definitions.ts, which is the single authoritative source of truth.
 *
 * Use this helper wherever you need to validate or filter a spawn candidate
 * against the active zone.
 */
export function getSpawnableEnemyTypesForZone(zoneId: RpgZoneId): readonly string[] {
  if (zoneId === 'euhedral') {
    // Euhedral: standard crystal enemies + elite crystal enemies + stardust + boss only.
    // Aliven particle swarms belong exclusively to the Impetus zone and must
    // never appear here.
    return [
      ...STANDARD_WAVE_ENEMY_IDS,
      ...ELITE_WAVE_ENEMY_IDS,
      'stardust',
      'boss',
    ];
  }
  const zoneDef = RPG_ZONE_BY_ID.get(zoneId);
  if (!zoneDef) return [];
  return zoneDef.enemyIds;
}
