export {
  createLoomState,
  getLoom,
  getUnlockedLooms,
  getLoomRate,
  getLoomCost,
  upgradeLoom,
  unlockLoom,
  tickLooms,
  isSpecialLoomPurchased,
  purchaseSpecialLoom,
  getLoomInputTierId,
  getLoomForInputTier,
  getLoomConversionThreshold,
  getLoomEfficiencyUpgradeCost,
  applyLoomCapture,
  tryUpgradeLoomEfficiency,
  MAX_LOOM_EFFICIENCY_LEVEL,
} from './loom-state';
export type { LoomState, LoomTierState } from './loom-state';
