/** Generated by scripts/generate-boss-music-track-manifest.mjs. Do not edit manually. */
export const BOSS_MUSIC_TRACKS_BY_BPM: Readonly<Record<number, readonly string[]>> = {
  "50": [
    "50BPM/BPM50-slimeyfox-midnight-high-score-487270.mp3"
  ],
  "60": [
    "60BPM/BPM60-psyai-cinematic-atmosphere-ambient-background-for-film-and-video-462156.mp3"
  ],
  "70": [
    "70BPM/BPM70-indigo-dusk.ogg"
  ],
  "80": [
    "80BPM/BPM80-verzand-horizon-99058.mp3"
  ],
  "90": [
    "90BPM/BPM90-jim_combs-the-80s-called-they-want-their-synths-back-140535.mp3",
    "90BPM/BPM90-onesevenbeatxs-slow-westcoast-boombap-type-beat-359448.mp3"
  ],
  "100": [
    "100BPM/BPM100-jasewhatson-void-protocol-473030.mp3",
    "100BPM/BPM100-leonarc-no-fearcinematic-hip-hop-beat-546425.mp3"
  ],
  "110": [
    "110BPM/BPM110-slimeyfox-hyperwoofer-ghost-engine-541639.mp3",
    "110BPM/BPM110-thisisbeatkitchen-my-heartbeat-110-bpm-instrumental-235079.mp3",
    "110BPM/BPM110-thisisbeatkitchen-summer-110-bpm-dancehall-instrumental-233181.mp3"
  ],
  "120": [
    "120BPM/BPM120-cekketto-enum3rato-469167.mp3",
    "120BPM/BPM120-erlanharmonies-heros-de-lx27ombre-290133.mp3",
    "120BPM/BPM120-keren_shteimberg-morning-drift-keren-shteimberg-547664.mp3",
    "120BPM/BPM120-trangiahung159-clockwork-pulse-536981.mp3"
  ],
  "130": [
    "130BPM/BPM130-apoprtv-free-for-profit-hiphop-synth-background-beat-130-bpm-110001.mp3",
    "130BPM/BPM130-justchilling1991-black-mamba-243827.mp3",
    "130BPM/BPM130-u_kw4gx9l0hh-i-fell-asleep-130bpm-276466.mp3"
  ],
  "140": [
    "140BPM/BPM140-cekketto-esper-451822.mp3",
    "140BPM/BPM140-kamhunt-trap-beat-1-140bpm-157804.mp3",
    "140BPM/BPM140-spyum-spyum-space-news-0x07-464642.mp3"
  ],
  "150": [
    "150BPM/BPM150-erlanharmonies-heros-de-lx27ombre-290133.mp3",
    "150BPM/BPM150-psychronic-binary-battle-404700.mp3",
    "150BPM/BPM150-psychronic-data-spike-481774.mp3",
    "150BPM/BPM150-psychronic-infinite-cosmos-404709.mp3",
    "150BPM/BPM150-psychronic-rebel-frequency-454812.mp3",
    "150BPM/BPM150-psychronic-terminus-engine-481773.mp3",
    "150BPM/BPM150-psychronic-the-sky-remembers-521619.mp3",
    "150BPM/BPM150-yoshiyuki_tatsuya-i-donx27t-like-nights-429605.mp3"
  ],
  "160": [
    "160BPM/BPM160-cg6-cyber-jump-499060.mp3",
    "160BPM/BPM160-mewwwwwww-angelic-frutiger-aero-554728.mp3",
    "160BPM/BPM160-quibsunmusic-tutur-donx27t-say-142792.mp3",
    "160BPM/BPM160-thisisbeatkitchen-beatkitchen-the-power-of-hope-160-bpm-377764.mp3"
  ],
  "170": [
    "170BPM/BPM170-beatkitchen-evening-with-girlfriend-gt-hip-hop-rap-instrumental-170-bpm-223310.mp3",
    "170BPM/BPM170-looksmusic-170-bpm-happy_-hard-core_-dj_-music_-2025-352678.mp3",
    "170BPM/BPM170-melodyayresgriffiths-hummingbird-game-loop-hiphop-piano-beat-56-seconds-170-bpm-110882.mp3",
    "170BPM/BPM170-yoshiyuki_tatsuya-high-peek-429685.mp3"
  ],
  "180": [
    "180BPM/BPM180-legendsquare-synthesis-287152.mp3"
  ]
};
