import {
  LASER_ENEMY_SIZE, LASER_ENEMY_COLOR, LASER_ENEMY_GLOW,
  SAPPHIRE_ENEMY_SIZE, SAPPHIRE_ENEMY_COLOR, SAPPHIRE_ENEMY_GLOW, SAPPHIRE_SHIELD_RADIUS,
  LASER_HP_INIT, LASER_ATK_INIT, LASER_DEF_INIT,
  SAPPHIRE_HP_INIT, SAPPHIRE_ATK_INIT, SAPPHIRE_DEF_INIT,
} from '../../render/rpg/rpg-constants';
import {
  DUSTWISP_HP_INIT, DUSTWISP_ATK_INIT, DUSTWISP_DEF_INIT, DUSTWISP_SIZE, DUSTWISP_COLOR, DUSTWISP_GLOW,
  RIBBONWORM_HP_INIT, RIBBONWORM_ATK_INIT, RIBBONWORM_DEF_INIT, RIBBONWORM_SIZE, RIBBONWORM_COLOR, RIBBONWORM_GLOW,
  LANTERNMOTH_HP_INIT, LANTERNMOTH_ATK_INIT, LANTERNMOTH_DEF_INIT, LANTERNMOTH_SIZE, LANTERNMOTH_COLOR, LANTERNMOTH_GLOW,
  EYESTALK_HP_INIT, EYESTALK_ATK_INIT, EYESTALK_DEF_INIT, EYESTALK_SIZE, EYESTALK_COLOR, EYESTALK_GLOW,
  JELLYFISH_HP_INIT, JELLYFISH_ATK_INIT, JELLYFISH_DEF_INIT, JELLYFISH_SIZE, JELLYFISH_COLOR, JELLYFISH_GLOW,
  CLOTHGHOST_HP_INIT, CLOTHGHOST_ATK_INIT, CLOTHGHOST_DEF_INIT, CLOTHGHOST_SIZE, CLOTHGHOST_COLOR, CLOTHGHOST_GLOW,
  PLANTTURRET_HP_INIT, PLANTTURRET_ATK_INIT, PLANTTURRET_DEF_INIT, PLANTTURRET_SIZE, PLANTTURRET_COLOR, PLANTTURRET_GLOW,
  GEARINSECT_HP_INIT, GEARINSECT_ATK_INIT, GEARINSECT_DEF_INIT, GEARINSECT_SIZE, GEARINSECT_COLOR, GEARINSECT_GLOW,
  SPIDERCRAWLER_HP_INIT, SPIDERCRAWLER_ATK_INIT, SPIDERCRAWLER_DEF_INIT, SPIDERCRAWLER_SIZE, SPIDERCRAWLER_COLOR, SPIDERCRAWLER_GLOW,
  MOTESWARM_HP_INIT, MOTESWARM_ATK_INIT, MOTESWARM_DEF_INIT, MOTESWARM_SIZE, MOTESWARM_COLOR, MOTESWARM_GLOW,
  SHADOWHAND_HP_INIT, SHADOWHAND_ATK_INIT, SHADOWHAND_DEF_INIT, SHADOWHAND_SIZE, SHADOWHAND_COLOR, SHADOWHAND_GLOW,
  SANDFISH_HP_INIT, SANDFISH_ATK_INIT, SANDFISH_DEF_INIT, SANDFISH_SIZE, SANDFISH_COLOR, SANDFISH_GLOW,
  QUARTZFISH_HP_INIT, QUARTZFISH_ATK_INIT, QUARTZFISH_DEF_INIT, QUARTZFISH_SIZE, QUARTZFISH_COLOR, QUARTZFISH_GLOW,
  RUBYFISH_HP_INIT, RUBYFISH_ATK_INIT, RUBYFISH_DEF_INIT, RUBYFISH_SIZE, RUBYFISH_COLOR, RUBYFISH_GLOW,
  SUNSTONEFISH_HP_INIT, SUNSTONEFISH_ATK_INIT, SUNSTONEFISH_DEF_INIT, SUNSTONEFISH_SIZE, SUNSTONEFISH_COLOR, SUNSTONEFISH_GLOW,
  EMERALDFISH_HP_INIT, EMERALDFISH_ATK_INIT, EMERALDFISH_DEF_INIT, EMERALDFISH_SIZE, EMERALDFISH_COLOR, EMERALDFISH_GLOW,
  SAPPHIREFISH_HP_INIT, SAPPHIREFISH_ATK_INIT, SAPPHIREFISH_DEF_INIT, SAPPHIREFISH_SIZE, SAPPHIREFISH_COLOR, SAPPHIREFISH_GLOW,
  AMETHYSTFISH_HP_INIT, AMETHYSTFISH_ATK_INIT, AMETHYSTFISH_DEF_INIT, AMETHYSTFISH_SIZE, AMETHYSTFISH_COLOR, AMETHYSTFISH_GLOW,
  DIAMONDFISH_HP_INIT, DIAMONDFISH_ATK_INIT, DIAMONDFISH_DEF_INIT, DIAMONDFISH_SIZE, DIAMONDFISH_COLOR, DIAMONDFISH_GLOW,
} from '../../render/rpg/rpg-procedural-constants';
import {
  EMERALD_ENEMY_SIZE, EMERALD_ENEMY_COLOR, EMERALD_ENEMY_GLOW,
  AMBER_ENEMY_SIZE, AMBER_ENEMY_COLOR, AMBER_ENEMY_GLOW,
  VOID_ENEMY_SIZE, VOID_ENEMY_COLOR, VOID_ENEMY_GLOW, VOID_AURA_RADIUS,
  QUARTZ_ENEMY_SIZE, QUARTZ_ENEMY_COLOR, QUARTZ_ENEMY_GLOW,
  RUBY_ENEMY_SIZE, RUBY_ENEMY_COLOR, RUBY_ENEMY_GLOW,
  SUNSTONE_ENEMY_SIZE, SUNSTONE_ENEMY_COLOR, SUNSTONE_ENEMY_GLOW,
  CITRINE_ENEMY_SIZE, CITRINE_ENEMY_COLOR, CITRINE_ENEMY_GLOW,
  IOLITE_ENEMY_SIZE, IOLITE_ENEMY_COLOR, IOLITE_ENEMY_GLOW,
  AMETHYST_ENEMY_SIZE, AMETHYST_ENEMY_COLOR, AMETHYST_ENEMY_GLOW,
  DIAMOND_ENEMY_SIZE, DIAMOND_ENEMY_COLOR, DIAMOND_ENEMY_GLOW,
  NULLSTONE_ENEMY_SIZE, NULLSTONE_ENEMY_COLOR, NULLSTONE_ENEMY_GLOW, NULLSTONE_GRAVITY_RADIUS,
  FRACTERYL_ENEMY_SIZE, FRACTERYL_ENEMY_COLOR, FRACTERYL_ENEMY_GLOW,
  EIGENSTEIN_ENEMY_SIZE, EIGENSTEIN_ENEMY_COLOR, EIGENSTEIN_ENEMY_GLOW,
  EMERALD_HP_INIT, EMERALD_ATK_INIT, EMERALD_DEF_INIT,
  AMBER_HP_INIT, AMBER_ATK_INIT, AMBER_DEF_INIT,
  VOID_HP_INIT, VOID_ATK_INIT, VOID_DEF_INIT,
  QUARTZ_HP_INIT, QUARTZ_ATK_INIT, QUARTZ_DEF_INIT,
  RUBY_HP_INIT, RUBY_ATK_INIT, RUBY_DEF_INIT,
  SUNSTONE_HP_INIT, SUNSTONE_ATK_INIT, SUNSTONE_DEF_INIT,
  CITRINE_HP_INIT, CITRINE_ATK_INIT, CITRINE_DEF_INIT,
  IOLITE_HP_INIT, IOLITE_ATK_INIT, IOLITE_DEF_INIT,
  AMETHYST_HP_INIT, AMETHYST_ATK_INIT, AMETHYST_DEF_INIT,
  DIAMOND_HP_INIT, DIAMOND_ATK_INIT, DIAMOND_DEF_INIT,
  NULLSTONE_HP_INIT, NULLSTONE_ATK_INIT, NULLSTONE_DEF_INIT,
  FRACTERYL_HP_INIT, FRACTERYL_ATK_INIT, FRACTERYL_DEF_INIT,
  EIGENSTEIN_HP_INIT, EIGENSTEIN_ATK_INIT, EIGENSTEIN_DEF_INIT,
  ELITE_QUARTZ_RADIUS, ELITE_QUARTZ_COLOR, ELITE_QUARTZ_GLOW,
  ELITE_QUARTZ_HP, ELITE_QUARTZ_ATK, ELITE_QUARTZ_DEF,
  ELITE_RUBY_RADIUS, ELITE_RUBY_COLOR, ELITE_RUBY_GLOW,
  ELITE_RUBY_HP, ELITE_RUBY_ATK, ELITE_RUBY_DEF,
  ELITE_SUNSTONE_RADIUS, ELITE_SUNSTONE_COLOR, ELITE_SUNSTONE_GLOW,
  ELITE_SUNSTONE_HP, ELITE_SUNSTONE_ATK, ELITE_SUNSTONE_DEF,
  ELITE_CITRINE_RADIUS, ELITE_CITRINE_COLOR, ELITE_CITRINE_GLOW,
  ELITE_CITRINE_HP, ELITE_CITRINE_ATK, ELITE_CITRINE_DEF,
  ELITE_IOLITE_RADIUS, ELITE_IOLITE_COLOR, ELITE_IOLITE_GLOW,
  ELITE_IOLITE_HP, ELITE_IOLITE_ATK, ELITE_IOLITE_DEF,
  ELITE_AMETHYST_RADIUS, ELITE_AMETHYST_COLOR, ELITE_AMETHYST_GLOW,
  ELITE_AMETHYST_HP, ELITE_AMETHYST_ATK, ELITE_AMETHYST_DEF,
  ELITE_DIAMOND_RADIUS, ELITE_DIAMOND_COLOR, ELITE_DIAMOND_GLOW,
  ELITE_DIAMOND_HP, ELITE_DIAMOND_ATK, ELITE_DIAMOND_DEF,
  ELITE_NULLSTONE_RADIUS, ELITE_NULLSTONE_COLOR, ELITE_NULLSTONE_GLOW,
  ELITE_NULLSTONE_HP, ELITE_NULLSTONE_ATK, ELITE_NULLSTONE_DEF,
} from '../../render/rpg/rpg-enemy-constants';
import type { EnemyCatalogEntry } from './rpg-enemies-catalog-types';

export const ENEMY_CATALOG: readonly EnemyCatalogEntry[] = [
  {
    id: 'laser',
    name: 'Laser Striker',
    color: LASER_ENEMY_COLOR,
    glowColor: LASER_ENEMY_GLOW,
    size: LASER_ENEMY_SIZE,
    hp: LASER_HP_INIT, atk: LASER_ATK_INIT, def: LASER_DEF_INIT,
    firstWave: 1,
    description: 'A nimble red assailant that dashes straight through the player, leaving a glowing curved trail.',
    shape: 'square',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Laser-Striker.png',
  },
  {
    id: 'quartz',
    name: 'Quartz Orbiter',
    color: QUARTZ_ENEMY_COLOR,
    glowColor: QUARTZ_ENEMY_GLOW,
    size: QUARTZ_ENEMY_SIZE,
    hp: QUARTZ_HP_INIT, atk: QUARTZ_ATK_INIT, def: QUARTZ_DEF_INIT,
    firstWave: 1,
    description: 'A pale crystal that strafe-orbits the player and periodically fires sharp spikes.',
    shape: 'diamond',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Quartz-Orbiter.png',
  },
  {
    id: 'sapphire',
    name: 'Sapphire Guard',
    color: SAPPHIRE_ENEMY_COLOR,
    glowColor: SAPPHIRE_ENEMY_GLOW,
    size: SAPPHIRE_ENEMY_SIZE,
    hp: SAPPHIRE_HP_INIT, atk: SAPPHIRE_ATK_INIT, def: SAPPHIRE_DEF_INIT,
    firstWave: 6,
    description: 'A shielded blue sentry that fires homing missiles while staying behind its protective barrier. Missiles chill on hit — repeated hits can freeze. Immune to Chilled; fire lenses are effective.',
    shape: 'square',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Sapphire-Guard.png',
    hasShield: true,
    shieldRadius: SAPPHIRE_SHIELD_RADIUS,
    shieldColor: SAPPHIRE_ENEMY_GLOW,
  },
  {
    id: 'emerald',
    name: 'Emerald Blinker',
    color: EMERALD_ENEMY_COLOR,
    glowColor: EMERALD_ENEMY_GLOW,
    size: EMERALD_ENEMY_SIZE,
    hp: EMERALD_HP_INIT, atk: EMERALD_ATK_INIT, def: EMERALD_DEF_INIT,
    firstWave: 9,
    description: 'A teleporting green sprite that charges briefly then blinks directly onto the player. Poisons on contact — resists poison lenses but is weak to fire.',
    shape: 'square',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Emerald-Blinker.png',
  },
  {
    id: 'ruby',
    name: 'Ruby Patroller',
    color: RUBY_ENEMY_COLOR,
    glowColor: RUBY_ENEMY_GLOW,
    size: RUBY_ENEMY_SIZE,
    hp: RUBY_HP_INIT, atk: RUBY_ATK_INIT, def: RUBY_DEF_INIT,
    firstWave: 10,
    description: 'A fast crimson marauder that closes range quickly and unleashes rapid bursts of fire bolts. Burns on hit — immune to Burning itself.',
    shape: 'square',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Ruby-Patroller.png',
  },
  {
    id: 'amber',
    name: 'Amber Gunner',
    color: AMBER_ENEMY_COLOR,
    glowColor: AMBER_ENEMY_GLOW,
    size: AMBER_ENEMY_SIZE,
    hp: AMBER_HP_INIT, atk: AMBER_ATK_INIT, def: AMBER_DEF_INIT,
    firstWave: 12,
    description: 'A stocky orange artillery unit that fires a spread of three homing shards in a fan.',
    shape: 'square',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Amber-Gunner.png',
  },
  {
    id: 'void',
    name: 'Void Bruiser',
    color: VOID_ENEMY_COLOR,
    glowColor: VOID_ENEMY_GLOW,
    size: VOID_ENEMY_SIZE,
    hp: VOID_HP_INIT, atk: VOID_ATK_INIT, def: VOID_DEF_INIT,
    firstWave: 15,
    description: 'A massive purple predator that relentlessly pursues the player and deals heavy contact damage.',
    shape: 'square',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Void-Bruiser.png',
    auraRadius: VOID_AURA_RADIUS,
  },
  {
    id: 'sunstone',
    name: 'Sunstone Orbiter',
    color: SUNSTONE_ENEMY_COLOR,
    glowColor: SUNSTONE_ENEMY_GLOW,
    size: SUNSTONE_ENEMY_SIZE,
    hp: SUNSTONE_HP_INIT, atk: SUNSTONE_ATK_INIT, def: SUNSTONE_DEF_INIT,
    firstWave: 20,
    description: 'A blazing orange planet-like enemy that circles at range and emits damaging area pulses.',
    shape: 'circle',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Sunstone-Orbiter.png',
  },
  {
    id: 'citrine',
    name: 'Citrine Chaser',
    color: CITRINE_ENEMY_COLOR,
    glowColor: CITRINE_ENEMY_GLOW,
    size: CITRINE_ENEMY_SIZE,
    hp: CITRINE_HP_INIT, atk: CITRINE_ATK_INIT, def: CITRINE_DEF_INIT,
    firstWave: 30,
    description: 'A swift golden tracker that patrols at high speed and launches homing bolts that curve toward the player.',
    shape: 'square',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Citrine-Chaser.png',
  },
  {
    id: 'iolite',
    name: 'Iolite Colossus',
    color: IOLITE_ENEMY_COLOR,
    glowColor: IOLITE_ENEMY_GLOW,
    size: IOLITE_ENEMY_SIZE,
    hp: IOLITE_HP_INIT, atk: IOLITE_ATK_INIT, def: IOLITE_DEF_INIT,
    firstWave: 40,
    description: 'A heavily armored indigo titan that fires a spread of five beams in a wide arc. Beams inflict Time-Warped, slowing attack cadence. Resists Time-Warped; vulnerable to Radiant lenses.',
    shape: 'circle',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Iolite-Colossus.png',
  },
  {
    id: 'amethyst',
    name: 'Amethyst Shielder',
    color: AMETHYST_ENEMY_COLOR,
    glowColor: AMETHYST_ENEMY_GLOW,
    size: AMETHYST_ENEMY_SIZE,
    hp: AMETHYST_HP_INIT, atk: AMETHYST_ATK_INIT, def: AMETHYST_DEF_INIT,
    firstWave: 50,
    description: 'A crystal-shielded violet tank that periodically shatters its own barrier into a burst of shards. Its resonant structure amplifies Echo-Marked — target it with amethyst lenses for extra burst.',
    shape: 'circle',
    zone: 'euhedral',
    hasShield: true,
    shieldRadius: AMETHYST_ENEMY_SIZE * 2.4,
    shieldColor: AMETHYST_ENEMY_GLOW,
    iconFile: 'EnemyIcon_Amethyst-Shielder.png',
  },
  {
    id: 'diamond',
    name: 'Diamond Phase-Shifter',
    color: DIAMOND_ENEMY_COLOR,
    glowColor: DIAMOND_ENEMY_GLOW,
    size: DIAMOND_ENEMY_SIZE,
    hp: DIAMOND_HP_INIT, atk: DIAMOND_ATK_INIT, def: DIAMOND_DEF_INIT,
    firstWave: 60,
    description: 'A prismatic phase-shifter that cycles between invulnerable and vulnerable states while firing orbiting shards. Its lattice resists Cracked but its polished surface is weak to Abraded.',
    shape: 'diamond',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Diamond-Phase-Shifter.png',
  },
  {
    id: 'nullstone',
    name: 'Nullstone Gravity Well',
    color: NULLSTONE_ENEMY_COLOR,
    glowColor: NULLSTONE_ENEMY_GLOW,
    size: NULLSTONE_ENEMY_SIZE,
    hp: NULLSTONE_HP_INIT, atk: NULLSTONE_ATK_INIT, def: NULLSTONE_DEF_INIT,
    firstWave: 70,
    description: 'A dark gravitational horror that pulls the player into its core and launches void tendrils. Tendrils inflict Slowed — resists Gravitized lenses but is vulnerable to Time-Warped.',
    shape: 'circle',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Nullstone-Gravity-Well.png',
    auraRadius: NULLSTONE_GRAVITY_RADIUS * 0.22,
  },
  {
    id: 'fracteryl',
    name: 'Fracteryl Manifestation',
    color: FRACTERYL_ENEMY_COLOR,
    glowColor: FRACTERYL_ENEMY_GLOW,
    size: FRACTERYL_ENEMY_SIZE,
    hp: FRACTERYL_HP_INIT, atk: FRACTERYL_ATK_INIT, def: FRACTERYL_DEF_INIT,
    firstWave: 74,
    description: 'A fractal purple entity that explodes into recursive shard storms that themselves split on impact. Its recursive nature resists Fractal Wound — Cracked lenses shatter its pattern effectively.',
    shape: 'diamond',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Fracteryl-Manifestation.png',
  },
  {
    id: 'eigenstein',
    name: 'Eigenstein Entity',
    color: EIGENSTEIN_ENEMY_COLOR,
    glowColor: EIGENSTEIN_ENEMY_GLOW,
    size: EIGENSTEIN_ENEMY_SIZE,
    hp: EIGENSTEIN_HP_INIT, atk: EIGENSTEIN_ATK_INIT, def: EIGENSTEIN_DEF_INIT,
    firstWave: 85,
    description: 'A transcendent cyan construct that charges a sweeping beam of pure mathematics before firing. Already quantum-scarred — Rift-Scarred stacks accumulate slower. Radiant light collapses its wave functions.',
    shape: 'circle',
    zone: 'euhedral',
    iconFile: 'EnemyIcon_Eigenstein-Entity.png',
  },
  {
    id: 'elite_quartz',
    name: 'Elite Quartz Orbiter',
    color: ELITE_QUARTZ_COLOR,
    glowColor: ELITE_QUARTZ_GLOW,
    size: ELITE_QUARTZ_RADIUS,
    hp: ELITE_QUARTZ_HP, atk: ELITE_QUARTZ_ATK, def: ELITE_QUARTZ_DEF,
    firstWave: 2,
    description: 'A crowned quartz crystal wreathed in a violet halo that fires double spike bursts with relentless precision.',
    shape: 'polygon',
    zone: 'euhedral',
    sides: 3,
    category: 'elite',
  },
  {
    id: 'elite_ruby',
    name: 'Elite Ruby Patroller',
    color: ELITE_RUBY_COLOR,
    glowColor: ELITE_RUBY_GLOW,
    size: ELITE_RUBY_RADIUS,
    hp: ELITE_RUBY_HP, atk: ELITE_RUBY_ATK, def: ELITE_RUBY_DEF,
    firstWave: 5,
    description: 'A blazing crimson hunter crowned in fire that charges at terrifying speed and unleashes devastating bolt salvos.',
    shape: 'polygon',
    zone: 'euhedral',
    sides: 4,
    category: 'elite',
  },
  {
    id: 'elite_sunstone',
    name: 'Elite Sunstone Orbiter',
    color: ELITE_SUNSTONE_COLOR,
    glowColor: ELITE_SUNSTONE_GLOW,
    size: ELITE_SUNSTONE_RADIUS,
    hp: ELITE_SUNSTONE_HP, atk: ELITE_SUNSTONE_ATK, def: ELITE_SUNSTONE_DEF,
    firstWave: 10,
    description: 'A searing elite sun that orbits at close range and floods the arena with overlapping area pulses.',
    shape: 'polygon',
    zone: 'euhedral',
    sides: 5,
    category: 'elite',
  },
  {
    id: 'elite_citrine',
    name: 'Elite Citrine Chaser',
    color: ELITE_CITRINE_COLOR,
    glowColor: ELITE_CITRINE_GLOW,
    size: ELITE_CITRINE_RADIUS,
    hp: ELITE_CITRINE_HP, atk: ELITE_CITRINE_ATK, def: ELITE_CITRINE_DEF,
    firstWave: 15,
    description: 'A golden elite tracker that barrages the player with double volleys of tightly curved homing bolts.',
    shape: 'polygon',
    zone: 'euhedral',
    sides: 6,
    category: 'elite',
  },
  {
    id: 'elite_iolite',
    name: 'Elite Iolite Colossus',
    color: ELITE_IOLITE_COLOR,
    glowColor: ELITE_IOLITE_GLOW,
    size: ELITE_IOLITE_RADIUS,
    hp: ELITE_IOLITE_HP, atk: ELITE_IOLITE_ATK, def: ELITE_IOLITE_DEF,
    firstWave: 33,
    description: 'A titanic indigo colossus that periodically deploys a crushing gravity well alongside its wide-arc beam barrage.',
    shape: 'polygon',
    zone: 'euhedral',
    sides: 7,
    category: 'elite',
  },
  {
    id: 'elite_amethyst',
    name: 'Elite Amethyst Shielder',
    color: ELITE_AMETHYST_COLOR,
    glowColor: ELITE_AMETHYST_GLOW,
    size: ELITE_AMETHYST_RADIUS,
    hp: ELITE_AMETHYST_HP, atk: ELITE_AMETHYST_ATK, def: ELITE_AMETHYST_DEF,
    firstWave: 42,
    description: 'A violet siege fortress that regenerates its massive shield and unleashes double ring-burst explosions on each break.',
    shape: 'polygon',
    zone: 'euhedral',
    sides: 8,
    hasShield: true,
    shieldRadius: ELITE_AMETHYST_RADIUS * 2.6,
    shieldColor: ELITE_AMETHYST_GLOW,
    category: 'elite',
  },
  {
    id: 'elite_diamond',
    name: 'Elite Diamond Phase-Shifter',
    color: ELITE_DIAMOND_COLOR,
    glowColor: ELITE_DIAMOND_GLOW,
    size: ELITE_DIAMOND_RADIUS,
    hp: ELITE_DIAMOND_HP, atk: ELITE_DIAMOND_ATK, def: ELITE_DIAMOND_DEF,
    firstWave: 52,
    description: 'A prismatic elite that orbits at blinding speed during invulnerability and fires a nine-star shard burst when vulnerable.',
    shape: 'polygon',
    zone: 'euhedral',
    sides: 9,
    category: 'elite',
  },
  {
    id: 'elite_nullstone',
    name: 'Elite Nullstone Gravity Well',
    color: ELITE_NULLSTONE_COLOR,
    glowColor: ELITE_NULLSTONE_GLOW,
    size: ELITE_NULLSTONE_RADIUS,
    hp: ELITE_NULLSTONE_HP, atk: ELITE_NULLSTONE_ATK, def: ELITE_NULLSTONE_DEF,
    firstWave: 63,
    description: 'An apex void entity that triggers Event Horizon singularity bursts and launches void tendrils from all directions.',
    shape: 'polygon',
    zone: 'euhedral',
    sides: 10,
    category: 'elite',
  },
  {
    id: 'verdure_polyomino',
    name: 'Verdure Polyomino',
    color: 'rgba(45,106,79,0.55)',
    glowColor: '#52b788',
    size: 22,
    hp: 490, atk: 26, def: 8,
    firstWave: 30,
    description: 'A slow-moving cluster of moss-green cells that expands one block at a time. Collides with the player on contact and cannot be outrun through narrow passages.',
    shape: 'square',
    zone: 'verdure',
    category: 'elite',
    iconFile: 'EnemyIcon_Verdure-Polyomino.png',
  },
  {
    id: 'verdure_polyomino_fissile',
    name: 'Fissile Polyomino',
    color: 'rgba(212,168,67,0.55)',
    glowColor: '#e9c46a',
    size: 22,
    hp: 578, atk: 27, def: 8,
    firstWave: 30,
    description: 'A gold-tinted polyomino cluster that periodically sheds a smaller fragment of itself. Destroying a Fissile Polyomino spawns two independent splinter clusters.',
    shape: 'square',
    zone: 'verdure',
    category: 'elite',
    iconFile: 'EnemyIcon_Fissile-Polyomino.png',
  },
  {
    id: 'verdure_polyomino_refractor',
    name: 'Refractor Polyomino',
    color: 'rgba(0,245,212,0.35)',
    glowColor: '#90e0ef',
    size: 22,
    hp: 465, atk: 30, def: 8,
    firstWave: 30,
    description: 'A cyan block cluster that fires sweeping laser beams from its outer cells. Each laser persists briefly and deals contact damage across its full length.',
    shape: 'square',
    zone: 'verdure',
    category: 'elite',
    iconFile: 'EnemyIcon_Refractor-Polyomino.png',
  },
  {
    id: 'aliven_spark_cluster',
    name: 'Aliven Spark Cluster',
    color: '#7ab4ff',
    glowColor: '#4488ee',
    size: 5,
    hp: 18, atk: 8, def: 0,
    firstWave: 2,
    description: 'A swarm of 8 alivened motes that drift and seek the player. Each spitter fires a slow, dodgeable bullet every 3–5 s. Defeat all particles to clear the group.',
    shape: 'circle',
    zone: 'impetus',
    iconFile: 'EnemyIcon_Aliven-Spark-Cluster.png',
  },
  {
    id: 'aliven_shard_bloom',
    name: 'Aliven Shard Bloom',
    color: '#44ee88',
    glowColor: '#22bb66',
    size: 6,
    hp: 28, atk: 12, def: 0,
    firstWave: 5,
    description: 'A crystalline swarm of 10 particles that periodically dash toward the player with staggered, randomised timing.',
    shape: 'circle',
    zone: 'impetus',
    iconFile: 'EnemyIcon_Aliven-Shard-Bloom.png',
  },
  {
    id: 'aliven_pulse_swarm',
    name: 'Aliven Pulse Swarm',
    color: '#f0d060',
    glowColor: '#c8a020',
    size: 6,
    hp: 38, atk: 14, def: 0,
    firstWave: 8,
    description: 'A citrine-hued swarm of 10 pulsers that emit area shockwaves on randomised cooldowns. The pulses deal bonus damage and stack dangerously at close range.',
    shape: 'circle',
    zone: 'impetus',
    iconFile: 'EnemyIcon_Aliven-Pulse-Swarm.png',
  },
  {
    id: 'aliven_ember_ring',
    name: 'Aliven Ember Ring',
    color: '#ff8c3c',
    glowColor: '#dd4400',
    size: 7,
    hp: 50, atk: 14, def: 0,
    firstWave: 12,
    description: 'A sunstone-tinted cluster of 10 ember particles that leave comet trails as they swirl. High contact damage — stay mobile.',
    shape: 'circle',
    zone: 'impetus',
    iconFile: 'EnemyIcon_Aliven-Ember-Ring.png',
  },
  {
    id: 'aliven_void_splinters',
    name: 'Aliven Void Splinters',
    color: '#9966bb',
    glowColor: '#6633aa',
    size: 5,
    hp: 65, atk: 16, def: 0,
    firstWave: 18,
    description: 'A void-tinted swarm of 12 splitter particles. Each particle that falls in battle erupts into 2 weaker child fragments — prioritise area weapons.',
    shape: 'circle',
    zone: 'impetus',
    iconFile: 'EnemyIcon_Aliven-Void-Splinters.png',
  },
  {
    id: 'aliven_healer_nodes',
    name: 'Aliven Healer Nodes',
    color: '#cc88ee',
    glowColor: '#aa55cc',
    size: 7,
    hp: 80, atk: 14, def: 0,
    firstWave: 22,
    description: 'An amethyst swarm of 9 particles including healer nodes that restore HP to nearby allies every few seconds. Eliminate healers first — they are marked with a faint outer ring.',
    shape: 'circle',
    zone: 'impetus',
    iconFile: 'EnemyIcon_Aliven-Healer-Nodes.png',
  },
  {
    id: 'aliven_orbit_bloom',
    name: 'Aliven Orbit Bloom',
    color: '#ff5050',
    glowColor: '#cc1111',
    size: 6,
    hp: 95, atk: 18, def: 0,
    firstWave: 28,
    description: 'A ruby-red swarm of 12 orbiter particles that circle a drifting centroid while relentlessly seeking the player. Beautiful and deadly.',
    shape: 'circle',
    zone: 'impetus',
    iconFile: 'EnemyIcon_Aliven-Orbit-Bloom.png',
  },
  {
    id: 'aliven_quartz_ghost',
    name: 'Aliven Quartz Ghost',
    color: '#d8e8f0',
    glowColor: '#aaccee',
    size: 6,
    hp: 22, atk: 10, def: 0,
    firstWave: 4,
    description: 'A pale quartz swarm of 10 particles that periodically phase into an invulnerable ghost state — time your attacks between their flickers.',
    shape: 'circle',
    zone: 'impetus',
    iconFile: 'EnemyIcon_Aliven-Quartz-Ghost.png',
  },
  {
    id: 'aliven_iolite_prism',
    name: 'Aliven Iolite Prism',
    color: '#6464b4',
    glowColor: '#8888cc',
    size: 6,
    hp: 80, atk: 18, def: 0,
    firstWave: 38,
    description: 'A dense iolite cluster of 14 pulser particles that simultaneously detonate area shockwaves — stay mobile or be overwhelmed.',
    shape: 'circle',
    zone: 'impetus',
    iconFile: 'EnemyIcon_Aliven-Iolite-Prism.png',
  },
  {
    id: 'aliven_fracteryl_storm',
    name: 'Aliven Fracteryl Storm',
    color: '#cc44ff',
    glowColor: '#ee88ff',
    size: 5,
    hp: 120, atk: 22, def: 0,
    firstWave: 65,
    description: 'A fractal cascade of 18 splitter particles that erupts into smaller fragments on death — dealing with one triggers two more.',
    shape: 'circle',
    zone: 'impetus',
    category: 'aliven',
    iconFile: 'EnemyIcon_Aliven-Fracteryl-Storm.png',
  },
  // ── Elite Aliven particle swarms (every 10th wave) ────────────────────────────
  // Elite variants share stats and specials with their base counterpart but retain
  // the player-seeking movement bias removed from normal groups. Marked with a
  // gold halo and crown indicator in-game.
  {
    id: 'aliven_elite_spark_cluster',
    name: 'Elite Aliven Spark Cluster',
    color: '#7ab4ff',
    glowColor: '#4488ee',
    size: 5,
    hp: 18, atk: 8, def: 0,
    firstWave: 10,
    description: 'A player-seeking sapphire spitter swarm. Unlike its normal counterpart, this elite actively homes toward the player while spitting bullets. Marked by a gold halo.',
    shape: 'circle',
    zone: 'impetus',
    category: 'elite',
    iconFile: 'EnemyIcon_Elite-Aliven-Spark-Cluster.png',
  },
  {
    id: 'aliven_elite_shard_bloom',
    name: 'Elite Aliven Shard Bloom',
    color: '#44ee88',
    glowColor: '#22bb66',
    size: 6,
    hp: 28, atk: 12, def: 0,
    firstWave: 10,
    description: 'A player-seeking emerald dasher swarm. Constantly homes toward the player and periodically bursts with a dash — doubly dangerous. Marked by a gold halo.',
    shape: 'circle',
    zone: 'impetus',
    category: 'elite',
  },
  {
    id: 'aliven_elite_pulse_swarm',
    name: 'Elite Aliven Pulse Swarm',
    color: '#f0d060',
    glowColor: '#c8a020',
    size: 6,
    hp: 38, atk: 14, def: 0,
    firstWave: 20,
    description: 'A player-seeking citrine pulser swarm. Homes in then detonates area shockwaves at close range. Avoid clustering — one pulse wave can cascade into several. Gold halo marks it as elite.',
    shape: 'circle',
    zone: 'impetus',
    category: 'elite',
  },
  {
    id: 'aliven_elite_ember_ring',
    name: 'Elite Aliven Ember Ring',
    color: '#ff8c3c',
    glowColor: '#dd4400',
    size: 7,
    hp: 50, atk: 14, def: 0,
    firstWave: 30,
    description: 'A player-seeking sunstone ember swarm. Leaves comet trails as it relentlessly pursues the player. High contact damage — stay mobile. Gold halo marks it as elite.',
    shape: 'circle',
    zone: 'impetus',
    category: 'elite',
  },
  {
    id: 'aliven_elite_void_splinters',
    name: 'Elite Aliven Void Splinters',
    color: '#9966bb',
    glowColor: '#6633aa',
    size: 5,
    hp: 65, atk: 16, def: 0,
    firstWave: 40,
    description: 'A player-seeking void splitter swarm. Constantly homes toward the player and spawns child fragments on death. Prioritise area weapons. Gold halo marks it as elite.',
    shape: 'circle',
    zone: 'impetus',
    category: 'elite',
  },
  {
    id: 'aliven_elite_healer_nodes',
    name: 'Elite Aliven Healer Nodes',
    color: '#cc88ee',
    glowColor: '#aa55cc',
    size: 7,
    hp: 80, atk: 14, def: 0,
    firstWave: 50,
    description: 'A player-seeking amethyst healer swarm. Homes toward the player while healers restore allies. Eliminate marked healers first. Gold halo marks it as elite.',
    shape: 'circle',
    zone: 'impetus',
    category: 'elite',
    iconFile: 'EnemyIcon_Aliven-Healer-Nodes.png',
  },
  {
    id: 'aliven_elite_orbit_bloom',
    name: 'Elite Aliven Orbit Bloom',
    color: '#ff5050',
    glowColor: '#cc1111',
    size: 6,
    hp: 95, atk: 18, def: 0,
    firstWave: 60,
    description: 'A player-seeking ruby orbiter swarm. Circles its centroid while that centroid itself homes toward the player — a spiralling, aggressive formation. Gold halo marks it as elite.',
    shape: 'circle',
    zone: 'impetus',
    category: 'elite',
  },
  {
    id: 'aliven_elite_quartz_ghost',
    name: 'Elite Aliven Quartz Ghost',
    color: '#d8e8f0',
    glowColor: '#aaccee',
    size: 6,
    hp: 22, atk: 10, def: 0,
    firstWave: 10,
    description: 'A player-seeking quartz ghost swarm. Phases invulnerable while closing the distance — time your damage windows carefully. Gold halo marks it as elite.',
    shape: 'circle',
    zone: 'impetus',
    category: 'elite',
  },
  {
    id: 'aliven_elite_iolite_prism',
    name: 'Elite Aliven Iolite Prism',
    color: '#6464b4',
    glowColor: '#8888cc',
    size: 6,
    hp: 80, atk: 18, def: 0,
    firstWave: 70,
    description: 'A player-seeking iolite pulser dense-cluster. Homes in and detonates simultaneous shockwaves at close range. Gold halo marks it as elite.',
    shape: 'circle',
    zone: 'impetus',
    category: 'elite',
  },
  {
    id: 'aliven_elite_fracteryl_storm',
    name: 'Elite Aliven Fracteryl Storm',
    color: '#cc44ff',
    glowColor: '#ee88ff',
    size: 5,
    hp: 120, atk: 22, def: 0,
    firstWave: 80,
    description: 'A player-seeking fracteryl splitter storm. Homes toward the player while cascading into child fragments on every death. Gold halo marks it as elite.',
    shape: 'circle',
    zone: 'impetus',
    category: 'elite',
  },
  // ── Procedural animated enemies ──────────────────────────────────────────────
  // These enemies are generated by the procedural wave generator (waves 26+).
  // They use custom animated draw functions rather than simple geometric icons.
  {
    id: 'proc_dustwisp',
    name: 'Dust Wisp',
    color: DUSTWISP_COLOR,
    glowColor: DUSTWISP_GLOW,
    size: DUSTWISP_SIZE,
    hp: DUSTWISP_HP_INIT, atk: DUSTWISP_ATK_INIT, def: DUSTWISP_DEF_INIT,
    firstWave: 26,
    description: 'A gentle drifting mote with a pulsing glow and three slow-orbit sparkle dots. Harmless-looking but dangerous at close range.',
    shape: 'circle',
    zone: 'impetus',
    category: 'procedural',
    iconFile: 'EnemyIcon_Dust-Wisp.png',
  },
  {
    id: 'proc_ribbonworm',
    name: 'Ribbon Worm',
    color: RIBBONWORM_COLOR,
    glowColor: RIBBONWORM_GLOW,
    size: RIBBONWORM_SIZE,
    hp: RIBBONWORM_HP_INIT, atk: RIBBONWORM_ATK_INIT, def: RIBBONWORM_DEF_INIT,
    firstWave: 26,
    description: 'A segmented worm with a glowing head that wiggles as it pursues the player through the arena.',
    shape: 'circle',
    zone: 'verdure',
    category: 'procedural',
    iconFile: 'EnemyIcon_Ribbon-Worm.png',
  },
  {
    id: 'proc_lanternmoth',
    name: 'Lantern Moth',
    color: LANTERNMOTH_COLOR,
    glowColor: LANTERNMOTH_GLOW,
    size: LANTERNMOTH_SIZE,
    hp: LANTERNMOTH_HP_INIT, atk: LANTERNMOTH_ATK_INIT, def: LANTERNMOTH_DEF_INIT,
    firstWave: 26,
    description: 'A floaty enemy with animated wing flaps and a warm teardrop body. Moves in a weaving sine-wave path.',
    shape: 'circle',
    zone: 'verdure',
    category: 'procedural',
    iconFile: 'EnemyIcon_Lantern-Moth.png',
  },
  {
    id: 'proc_eyestalk',
    name: 'Eye Stalk',
    color: EYESTALK_COLOR,
    glowColor: EYESTALK_GLOW,
    size: EYESTALK_SIZE,
    hp: EYESTALK_HP_INIT, atk: EYESTALK_ATK_INIT, def: EYESTALK_DEF_INIT,
    firstWave: 26,
    description: 'A round blob body with a spring-swaying eye stalk that eerily tracks the player across the arena.',
    shape: 'circle',
    zone: 'verdure',
    category: 'procedural',
    iconFile: 'EnemyIcon_Eye-Stalk.png',
  },
  {
    id: 'proc_jellyfish',
    name: 'Floating Jellyfish',
    color: JELLYFISH_COLOR,
    glowColor: JELLYFISH_GLOW,
    size: JELLYFISH_SIZE,
    hp: JELLYFISH_HP_INIT, atk: JELLYFISH_ATK_INIT, def: JELLYFISH_DEF_INIT,
    firstWave: 26,
    description: 'A transparent bell that pulses open and closed with trailing tentacles. Drifts deceptively slowly.',
    shape: 'circle',
    zone: 'caustics',
    category: 'procedural',
    iconFile: 'EnemyIcon_Floating-Jellyfish.png',
  },
  {
    id: 'proc_clothghost',
    name: 'Cloth Ghost',
    color: CLOTHGHOST_COLOR,
    glowColor: CLOTHGHOST_GLOW,
    size: CLOTHGHOST_SIZE,
    hp: CLOTHGHOST_HP_INIT, atk: CLOTHGHOST_ATK_INIT, def: CLOTHGHOST_DEF_INIT,
    firstWave: 26,
    description: 'A translucent cloth sheet that flutters and ripples as it glides silently toward the player.',
    shape: 'circle',
    zone: 'verdure',
    category: 'procedural',
    iconFile: 'EnemyIcon_Cloth-Ghost.png',
  },
  {
    id: 'proc_plantturret',
    name: 'Plant Turret',
    color: PLANTTURRET_COLOR,
    glowColor: PLANTTURRET_GLOW,
    size: PLANTTURRET_SIZE,
    hp: PLANTTURRET_HP_INIT, atk: PLANTTURRET_ATK_INIT, def: PLANTTURRET_DEF_INIT,
    firstWave: 26,
    description: 'A stationary root-anchored plant that sways gently and periodically fires spore projectiles at the player.',
    shape: 'circle',
    zone: 'verdure',
    category: 'procedural',
    iconFile: 'EnemyIcon_Plant-Turret.png',
  },
  {
    id: 'proc_gearinsect',
    name: 'Gear Insect',
    color: GEARINSECT_COLOR,
    glowColor: GEARINSECT_GLOW,
    size: GEARINSECT_SIZE,
    hp: GEARINSECT_HP_INIT, atk: GEARINSECT_ATK_INIT, def: GEARINSECT_DEF_INIT,
    firstWave: 26,
    description: 'A mechanical bug with a spinning central gear and six oscillating insect legs that skitter across the arena.',
    shape: 'circle',
    zone: 'verdure',
    category: 'procedural',
    iconFile: 'EnemyIcon_Gear-Insect.png',
  },
  {
    id: 'proc_spidercrawler',
    name: 'Spider Crawler',
    color: SPIDERCRAWLER_COLOR,
    glowColor: SPIDERCRAWLER_GLOW,
    size: SPIDERCRAWLER_SIZE,
    hp: SPIDERCRAWLER_HP_INIT, atk: SPIDERCRAWLER_ATK_INIT, def: SPIDERCRAWLER_DEF_INIT,
    firstWave: 26,
    description: 'An eight-legged spider with an alternating walking cycle that relentlessly closes the gap to the player.',
    shape: 'circle',
    zone: 'verdure',
    category: 'procedural',
    iconFile: 'EnemyIcon_Spider-Crawler.png',
  },
  {
    id: 'proc_moteswarm',
    name: 'Magnetic Swarm',
    color: MOTESWARM_COLOR,
    glowColor: MOTESWARM_GLOW,
    size: MOTESWARM_SIZE,
    hp: MOTESWARM_HP_INIT, atk: MOTESWARM_ATK_INIT, def: MOTESWARM_DEF_INIT,
    firstWave: 26,
    description: 'A cluster of orbiting charged motes around a glowing core that slowly spirals toward the player.',
    shape: 'circle',
    zone: 'impetus',
    category: 'procedural',
    iconFile: 'EnemyIcon_Magnetic-Swarm.png',
  },
  {
    id: 'proc_shadowhand',
    name: 'Shadow Hand',
    color: SHADOWHAND_COLOR,
    glowColor: SHADOWHAND_GLOW,
    size: SHADOWHAND_SIZE,
    hp: SHADOWHAND_HP_INIT, atk: SHADOWHAND_ATK_INIT, def: SHADOWHAND_DEF_INIT,
    firstWave: 32,
    description: 'A disembodied dark hand that slowly reaches toward the player before grasping with outstretched fingers.',
    shape: 'circle',
    zone: 'impetus',
    category: 'procedural',
    iconFile: 'EnemyIcon_Shadow-Hand.png',
  },
  {
    id: 'proc_sandfish',
    name: 'Sand Fish',
    color: SANDFISH_COLOR,
    glowColor: SANDFISH_GLOW,
    size: SANDFISH_SIZE,
    hp: SANDFISH_HP_INIT, atk: SANDFISH_ATK_INIT, def: SANDFISH_DEF_INIT,
    firstWave: 34,
    description: 'A quick dune-colored fish that darts in curved paths, then suddenly lunges through the arena.',
    shape: 'circle',
    zone: 'caustics',
    category: 'procedural',
    iconFile: 'EnemyIcon_Sand-Fish.png',
  },
  {
    id: 'proc_quartzfish',
    name: 'Quartz Fish',
    color: QUARTZFISH_COLOR,
    glowColor: QUARTZFISH_GLOW,
    size: QUARTZFISH_SIZE,
    hp: QUARTZFISH_HP_INIT, atk: QUARTZFISH_ATK_INIT, def: QUARTZFISH_DEF_INIT,
    firstWave: 38,
    description: 'A pale crystal fish protected by a shimmering shell that must be cracked before it falls quickly.',
    shape: 'circle',
    zone: 'caustics',
    category: 'procedural',
    iconFile: 'EnemyIcon_Quartz-Fish.png',
  },
  {
    id: 'proc_rubyfish',
    name: 'Ruby Fish',
    color: RUBYFISH_COLOR,
    glowColor: RUBYFISH_GLOW,
    size: RUBYFISH_SIZE,
    hp: RUBYFISH_HP_INIT, atk: RUBYFISH_ATK_INIT, def: RUBYFISH_DEF_INIT,
    firstWave: 42,
    description: 'An aggressive crimson fish that winds up before bursting into a straight-line dash. Burns on contact — immune to Burning; weak to Chilled.',
    shape: 'circle',
    zone: 'caustics',
    category: 'procedural',
    iconFile: 'EnemyIcon_Ruby-Fish.png',
  },
  {
    id: 'proc_sunstonefish',
    name: 'Sunstone Fish',
    color: SUNSTONEFISH_COLOR,
    glowColor: SUNSTONEFISH_GLOW,
    size: SUNSTONEFISH_SIZE,
    hp: SUNSTONEFISH_HP_INIT, atk: SUNSTONEFISH_ATK_INIT, def: SUNSTONEFISH_DEF_INIT,
    firstWave: 46,
    description: 'A blazing orange swimmer that seeds the arena with armed mines that erupt into spikes.',
    shape: 'circle',
    zone: 'caustics',
    category: 'procedural',
    iconFile: 'EnemyIcon_Sunstone-Fish.png',
  },
  {
    id: 'proc_emeraldfish',
    name: 'Emerald Fish',
    color: EMERALDFISH_COLOR,
    glowColor: EMERALDFISH_GLOW,
    size: EMERALDFISH_SIZE,
    hp: EMERALDFISH_HP_INIT, atk: EMERALDFISH_ATK_INIT, def: EMERALDFISH_DEF_INIT,
    firstWave: 50,
    description: 'A green hunter that splinters into smaller fry when destroyed, preserving pressure after the kill. Poisons on contact — resists poison lenses; fire lenses deal extra damage.',
    shape: 'circle',
    zone: 'caustics',
    category: 'procedural',
    iconFile: 'EnemyIcon_Emerald-Fish.png',
  },
  {
    id: 'proc_sapphirefish',
    name: 'Sapphire Fish',
    color: SAPPHIREFISH_COLOR,
    glowColor: SAPPHIREFISH_GLOW,
    size: SAPPHIREFISH_SIZE,
    hp: SAPPHIREFISH_HP_INIT, atk: SAPPHIREFISH_ATK_INIT, def: SAPPHIREFISH_DEF_INIT,
    firstWave: 54,
    description: "A deep-blue fish that releases slow homing bolts while circling just outside the player’s path. Bolts chill on hit — repeated chills can freeze. Immune to Chilled; fire lenses are effective.",
    shape: 'circle',
    zone: 'caustics',
    category: 'procedural',
    iconFile: 'EnemyIcon_Sapphire-Fish.png',
  },
  {
    id: 'proc_amethystfish',
    name: 'Amethyst Fish',
    color: AMETHYSTFISH_COLOR,
    glowColor: AMETHYSTFISH_GLOW,
    size: AMETHYSTFISH_SIZE,
    hp: AMETHYSTFISH_HP_INIT, atk: AMETHYSTFISH_ATK_INIT, def: AMETHYSTFISH_DEF_INIT,
    firstWave: 58,
    description: 'A violet mirage fish that leaves a fading decoy behind whenever it teleports around the player.',
    shape: 'circle',
    zone: 'caustics',
    category: 'procedural',
    iconFile: 'EnemyIcon_Amethyst-Fish.png',
  },
  {
    id: 'proc_diamondfish',
    name: 'Diamond Fish',
    color: DIAMONDFISH_COLOR,
    glowColor: DIAMONDFISH_GLOW,
    size: DIAMONDFISH_SIZE,
    hp: DIAMONDFISH_HP_INIT, atk: DIAMONDFISH_ATK_INIT, def: DIAMONDFISH_DEF_INIT,
    firstWave: 62,
    description: 'A prismatic leviathan whose crystalline armor cycles on and off, heavily reducing incoming damage while active.',
    shape: 'circle',
    zone: 'caustics',
    category: 'procedural',
    iconFile: 'EnemyIcon_Diamond-Fish.png',
  },
] as const;
