import {
  LASER_ENEMY_SIZE, LASER_ENEMY_COLOR, LASER_ENEMY_GLOW,
  SAPPHIRE_ENEMY_SIZE, SAPPHIRE_ENEMY_COLOR, SAPPHIRE_ENEMY_GLOW, SAPPHIRE_SHIELD_RADIUS,
  LASER_HP_INIT, LASER_ATK_INIT, LASER_DEF_INIT,
  SAPPHIRE_HP_INIT, SAPPHIRE_ATK_INIT, SAPPHIRE_DEF_INIT,
} from '../../render/rpg/rpg-constants';
import {
  EMERALD_ENEMY_SIZE, EMERALD_ENEMY_COLOR, EMERALD_ENEMY_GLOW,
  AMBER_ENEMY_SIZE, AMBER_ENEMY_COLOR, AMBER_ENEMY_GLOW,
  VOID_ENEMY_SIZE, VOID_ENEMY_COLOR, VOID_ENEMY_GLOW, VOID_AURA_RADIUS,
  QUARTZ_ENEMY_SIZE, QUARTZ_ENEMY_COLOR, QUARTZ_ENEMY_GLOW,
  RUBY_ENEMY_SIZE, RUBY_ENEMY_COLOR, RUBY_ENEMY_GLOW,
  SUNSTONE_ENEMY_SIZE, SUNSTONE_ENEMY_COLOR, SUNSTONE_ENEMY_GLOW,
  CITRINE_ENEMY_SIZE, CITRINE_ENEMY_COLOR, CITRINE_ENEMY_GLOW,
  IOLITE_ENEMY_SIZE, IOLITE_ENEMY_COLOR, IOLITE_ENEMY_GLOW,
  AMETHYST_ENEMY_SIZE, AMETHYST_ENEMY_COLOR, AMETHYST_ENEMY_GLOW,
  DIAMOND_ENEMY_SIZE, DIAMOND_ENEMY_COLOR, DIAMOND_ENEMY_GLOW,
  NULLSTONE_ENEMY_SIZE, NULLSTONE_ENEMY_COLOR, NULLSTONE_ENEMY_GLOW, NULLSTONE_GRAVITY_RADIUS,
  FRACTERYL_ENEMY_SIZE, FRACTERYL_ENEMY_COLOR, FRACTERYL_ENEMY_GLOW,
  EIGENSTEIN_ENEMY_SIZE, EIGENSTEIN_ENEMY_COLOR, EIGENSTEIN_ENEMY_GLOW,
  EMERALD_HP_INIT, EMERALD_ATK_INIT, EMERALD_DEF_INIT,
  AMBER_HP_INIT, AMBER_ATK_INIT, AMBER_DEF_INIT,
  VOID_HP_INIT, VOID_ATK_INIT, VOID_DEF_INIT,
  QUARTZ_HP_INIT, QUARTZ_ATK_INIT, QUARTZ_DEF_INIT,
  RUBY_HP_INIT, RUBY_ATK_INIT, RUBY_DEF_INIT,
  SUNSTONE_HP_INIT, SUNSTONE_ATK_INIT, SUNSTONE_DEF_INIT,
  CITRINE_HP_INIT, CITRINE_ATK_INIT, CITRINE_DEF_INIT,
  IOLITE_HP_INIT, IOLITE_ATK_INIT, IOLITE_DEF_INIT,
  AMETHYST_HP_INIT, AMETHYST_ATK_INIT, AMETHYST_DEF_INIT,
  DIAMOND_HP_INIT, DIAMOND_ATK_INIT, DIAMOND_DEF_INIT,
  NULLSTONE_HP_INIT, NULLSTONE_ATK_INIT, NULLSTONE_DEF_INIT,
  FRACTERYL_HP_INIT, FRACTERYL_ATK_INIT, FRACTERYL_DEF_INIT,
  EIGENSTEIN_HP_INIT, EIGENSTEIN_ATK_INIT, EIGENSTEIN_DEF_INIT,
  ELITE_QUARTZ_RADIUS, ELITE_QUARTZ_COLOR, ELITE_QUARTZ_GLOW,
  ELITE_QUARTZ_HP, ELITE_QUARTZ_ATK, ELITE_QUARTZ_DEF,
  ELITE_RUBY_RADIUS, ELITE_RUBY_COLOR, ELITE_RUBY_GLOW,
  ELITE_RUBY_HP, ELITE_RUBY_ATK, ELITE_RUBY_DEF,
  ELITE_SUNSTONE_RADIUS, ELITE_SUNSTONE_COLOR, ELITE_SUNSTONE_GLOW,
  ELITE_SUNSTONE_HP, ELITE_SUNSTONE_ATK, ELITE_SUNSTONE_DEF,
  ELITE_CITRINE_RADIUS, ELITE_CITRINE_COLOR, ELITE_CITRINE_GLOW,
  ELITE_CITRINE_HP, ELITE_CITRINE_ATK, ELITE_CITRINE_DEF,
  ELITE_IOLITE_RADIUS, ELITE_IOLITE_COLOR, ELITE_IOLITE_GLOW,
  ELITE_IOLITE_HP, ELITE_IOLITE_ATK, ELITE_IOLITE_DEF,
  ELITE_AMETHYST_RADIUS, ELITE_AMETHYST_COLOR, ELITE_AMETHYST_GLOW,
  ELITE_AMETHYST_HP, ELITE_AMETHYST_ATK, ELITE_AMETHYST_DEF,
  ELITE_DIAMOND_RADIUS, ELITE_DIAMOND_COLOR, ELITE_DIAMOND_GLOW,
  ELITE_DIAMOND_HP, ELITE_DIAMOND_ATK, ELITE_DIAMOND_DEF,
  ELITE_NULLSTONE_RADIUS, ELITE_NULLSTONE_COLOR, ELITE_NULLSTONE_GLOW,
  ELITE_NULLSTONE_HP, ELITE_NULLSTONE_ATK, ELITE_NULLSTONE_DEF,
} from '../../render/rpg/rpg-enemy-constants';
import type { EnemyCatalogEntry } from './rpg-enemies-catalog-types';

export const ENEMY_CATALOG: readonly EnemyCatalogEntry[] = [
  {
    id: 'laser',
    name: 'Laser Striker',
    color: LASER_ENEMY_COLOR,
    glowColor: LASER_ENEMY_GLOW,
    size: LASER_ENEMY_SIZE,
    hp: LASER_HP_INIT, atk: LASER_ATK_INIT, def: LASER_DEF_INIT,
    firstWave: 1,
    description: 'A nimble red assailant that dashes straight through the player, leaving a glowing curved trail.',
    shape: 'square',
  },
  {
    id: 'quartz',
    name: 'Quartz Orbiter',
    color: QUARTZ_ENEMY_COLOR,
    glowColor: QUARTZ_ENEMY_GLOW,
    size: QUARTZ_ENEMY_SIZE,
    hp: QUARTZ_HP_INIT, atk: QUARTZ_ATK_INIT, def: QUARTZ_DEF_INIT,
    firstWave: 1,
    description: 'A pale crystal that strafe-orbits the player and periodically fires sharp spikes.',
    shape: 'diamond',
  },
  {
    id: 'sapphire',
    name: 'Sapphire Guard',
    color: SAPPHIRE_ENEMY_COLOR,
    glowColor: SAPPHIRE_ENEMY_GLOW,
    size: SAPPHIRE_ENEMY_SIZE,
    hp: SAPPHIRE_HP_INIT, atk: SAPPHIRE_ATK_INIT, def: SAPPHIRE_DEF_INIT,
    firstWave: 6,
    description: 'A shielded blue sentry that fires homing missiles while staying behind its protective barrier.',
    shape: 'square',
    hasShield: true,
    shieldRadius: SAPPHIRE_SHIELD_RADIUS,
    shieldColor: SAPPHIRE_ENEMY_GLOW,
  },
  {
    id: 'emerald',
    name: 'Emerald Blinker',
    color: EMERALD_ENEMY_COLOR,
    glowColor: EMERALD_ENEMY_GLOW,
    size: EMERALD_ENEMY_SIZE,
    hp: EMERALD_HP_INIT, atk: EMERALD_ATK_INIT, def: EMERALD_DEF_INIT,
    firstWave: 9,
    description: 'A teleporting green sprite that charges briefly then blinks directly onto the player.',
    shape: 'square',
  },
  {
    id: 'ruby',
    name: 'Ruby Patroller',
    color: RUBY_ENEMY_COLOR,
    glowColor: RUBY_ENEMY_GLOW,
    size: RUBY_ENEMY_SIZE,
    hp: RUBY_HP_INIT, atk: RUBY_ATK_INIT, def: RUBY_DEF_INIT,
    firstWave: 10,
    description: 'A fast crimson marauder that closes range quickly and unleashes rapid bursts of bolts.',
    shape: 'square',
  },
  {
    id: 'amber',
    name: 'Amber Gunner',
    color: AMBER_ENEMY_COLOR,
    glowColor: AMBER_ENEMY_GLOW,
    size: AMBER_ENEMY_SIZE,
    hp: AMBER_HP_INIT, atk: AMBER_ATK_INIT, def: AMBER_DEF_INIT,
    firstWave: 12,
    description: 'A stocky orange artillery unit that fires a spread of three homing shards in a fan.',
    shape: 'square',
  },
  {
    id: 'void',
    name: 'Void Bruiser',
    color: VOID_ENEMY_COLOR,
    glowColor: VOID_ENEMY_GLOW,
    size: VOID_ENEMY_SIZE,
    hp: VOID_HP_INIT, atk: VOID_ATK_INIT, def: VOID_DEF_INIT,
    firstWave: 15,
    description: 'A massive purple predator that relentlessly pursues the player and deals heavy contact damage.',
    shape: 'square',
    auraRadius: VOID_AURA_RADIUS,
  },
  {
    id: 'sunstone',
    name: 'Sunstone Orbiter',
    color: SUNSTONE_ENEMY_COLOR,
    glowColor: SUNSTONE_ENEMY_GLOW,
    size: SUNSTONE_ENEMY_SIZE,
    hp: SUNSTONE_HP_INIT, atk: SUNSTONE_ATK_INIT, def: SUNSTONE_DEF_INIT,
    firstWave: 20,
    description: 'A blazing orange planet-like enemy that circles at range and emits damaging area pulses.',
    shape: 'circle',
  },
  {
    id: 'citrine',
    name: 'Citrine Chaser',
    color: CITRINE_ENEMY_COLOR,
    glowColor: CITRINE_ENEMY_GLOW,
    size: CITRINE_ENEMY_SIZE,
    hp: CITRINE_HP_INIT, atk: CITRINE_ATK_INIT, def: CITRINE_DEF_INIT,
    firstWave: 30,
    description: 'A swift golden tracker that patrols at high speed and launches homing bolts that curve toward the player.',
    shape: 'square',
  },
  {
    id: 'iolite',
    name: 'Iolite Colossus',
    color: IOLITE_ENEMY_COLOR,
    glowColor: IOLITE_ENEMY_GLOW,
    size: IOLITE_ENEMY_SIZE,
    hp: IOLITE_HP_INIT, atk: IOLITE_ATK_INIT, def: IOLITE_DEF_INIT,
    firstWave: 40,
    description: 'A heavily armored indigo titan that fires a spread of five beams in a wide arc.',
    shape: 'circle',
  },
  {
    id: 'amethyst',
    name: 'Amethyst Shielder',
    color: AMETHYST_ENEMY_COLOR,
    glowColor: AMETHYST_ENEMY_GLOW,
    size: AMETHYST_ENEMY_SIZE,
    hp: AMETHYST_HP_INIT, atk: AMETHYST_ATK_INIT, def: AMETHYST_DEF_INIT,
    firstWave: 50,
    description: 'A crystal-shielded violet tank that periodically shatters its own barrier into a burst of shards.',
    shape: 'circle',
    hasShield: true,
    shieldRadius: AMETHYST_ENEMY_SIZE * 2.4,
    shieldColor: AMETHYST_ENEMY_GLOW,
  },
  {
    id: 'diamond',
    name: 'Diamond Phase-Shifter',
    color: DIAMOND_ENEMY_COLOR,
    glowColor: DIAMOND_ENEMY_GLOW,
    size: DIAMOND_ENEMY_SIZE,
    hp: DIAMOND_HP_INIT, atk: DIAMOND_ATK_INIT, def: DIAMOND_DEF_INIT,
    firstWave: 60,
    description: 'A prismatic phase-shifter that cycles between invulnerable and vulnerable states while firing orbiting shards.',
    shape: 'diamond',
  },
  {
    id: 'nullstone',
    name: 'Nullstone Gravity Well',
    color: NULLSTONE_ENEMY_COLOR,
    glowColor: NULLSTONE_ENEMY_GLOW,
    size: NULLSTONE_ENEMY_SIZE,
    hp: NULLSTONE_HP_INIT, atk: NULLSTONE_ATK_INIT, def: NULLSTONE_DEF_INIT,
    firstWave: 70,
    description: 'A dark gravitational horror that pulls the player into its core and launches void tendrils.',
    shape: 'circle',
    auraRadius: NULLSTONE_GRAVITY_RADIUS * 0.22,
  },
  {
    id: 'fracteryl',
    name: 'Fracteryl Manifestation',
    color: FRACTERYL_ENEMY_COLOR,
    glowColor: FRACTERYL_ENEMY_GLOW,
    size: FRACTERYL_ENEMY_SIZE,
    hp: FRACTERYL_HP_INIT, atk: FRACTERYL_ATK_INIT, def: FRACTERYL_DEF_INIT,
    firstWave: 74,
    description: 'A fractal purple entity that explodes into recursive shard storms that themselves split on impact.',
    shape: 'diamond',
  },
  {
    id: 'eigenstein',
    name: 'Eigenstein Entity',
    color: EIGENSTEIN_ENEMY_COLOR,
    glowColor: EIGENSTEIN_ENEMY_GLOW,
    size: EIGENSTEIN_ENEMY_SIZE,
    hp: EIGENSTEIN_HP_INIT, atk: EIGENSTEIN_ATK_INIT, def: EIGENSTEIN_DEF_INIT,
    firstWave: 85,
    description: 'A transcendent cyan construct that charges a sweeping beam of pure mathematics before firing.',
    shape: 'circle',
  },
  {
    id: 'elite_quartz',
    name: 'Elite Quartz Orbiter',
    color: ELITE_QUARTZ_COLOR,
    glowColor: ELITE_QUARTZ_GLOW,
    size: ELITE_QUARTZ_RADIUS,
    hp: ELITE_QUARTZ_HP, atk: ELITE_QUARTZ_ATK, def: ELITE_QUARTZ_DEF,
    firstWave: 2,
    description: 'A crowned quartz crystal wreathed in a violet halo that fires double spike bursts with relentless precision.',
    shape: 'polygon',
    sides: 3,
  },
  {
    id: 'elite_ruby',
    name: 'Elite Ruby Patroller',
    color: ELITE_RUBY_COLOR,
    glowColor: ELITE_RUBY_GLOW,
    size: ELITE_RUBY_RADIUS,
    hp: ELITE_RUBY_HP, atk: ELITE_RUBY_ATK, def: ELITE_RUBY_DEF,
    firstWave: 5,
    description: 'A blazing crimson hunter crowned in fire that charges at terrifying speed and unleashes devastating bolt salvos.',
    shape: 'polygon',
    sides: 4,
  },
  {
    id: 'elite_sunstone',
    name: 'Elite Sunstone Orbiter',
    color: ELITE_SUNSTONE_COLOR,
    glowColor: ELITE_SUNSTONE_GLOW,
    size: ELITE_SUNSTONE_RADIUS,
    hp: ELITE_SUNSTONE_HP, atk: ELITE_SUNSTONE_ATK, def: ELITE_SUNSTONE_DEF,
    firstWave: 10,
    description: 'A searing elite sun that orbits at close range and floods the arena with overlapping area pulses.',
    shape: 'polygon',
    sides: 5,
  },
  {
    id: 'elite_citrine',
    name: 'Elite Citrine Chaser',
    color: ELITE_CITRINE_COLOR,
    glowColor: ELITE_CITRINE_GLOW,
    size: ELITE_CITRINE_RADIUS,
    hp: ELITE_CITRINE_HP, atk: ELITE_CITRINE_ATK, def: ELITE_CITRINE_DEF,
    firstWave: 15,
    description: 'A golden elite tracker that barrages the player with double volleys of tightly curved homing bolts.',
    shape: 'polygon',
    sides: 6,
  },
  {
    id: 'elite_iolite',
    name: 'Elite Iolite Colossus',
    color: ELITE_IOLITE_COLOR,
    glowColor: ELITE_IOLITE_GLOW,
    size: ELITE_IOLITE_RADIUS,
    hp: ELITE_IOLITE_HP, atk: ELITE_IOLITE_ATK, def: ELITE_IOLITE_DEF,
    firstWave: 33,
    description: 'A titanic indigo colossus that periodically deploys a crushing gravity well alongside its wide-arc beam barrage.',
    shape: 'polygon',
    sides: 7,
  },
  {
    id: 'elite_amethyst',
    name: 'Elite Amethyst Shielder',
    color: ELITE_AMETHYST_COLOR,
    glowColor: ELITE_AMETHYST_GLOW,
    size: ELITE_AMETHYST_RADIUS,
    hp: ELITE_AMETHYST_HP, atk: ELITE_AMETHYST_ATK, def: ELITE_AMETHYST_DEF,
    firstWave: 42,
    description: 'A violet siege fortress that regenerates its massive shield and unleashes double ring-burst explosions on each break.',
    shape: 'polygon',
    sides: 8,
    hasShield: true,
    shieldRadius: ELITE_AMETHYST_RADIUS * 2.6,
    shieldColor: ELITE_AMETHYST_GLOW,
  },
  {
    id: 'elite_diamond',
    name: 'Elite Diamond Phase-Shifter',
    color: ELITE_DIAMOND_COLOR,
    glowColor: ELITE_DIAMOND_GLOW,
    size: ELITE_DIAMOND_RADIUS,
    hp: ELITE_DIAMOND_HP, atk: ELITE_DIAMOND_ATK, def: ELITE_DIAMOND_DEF,
    firstWave: 52,
    description: 'A prismatic elite that orbits at blinding speed during invulnerability and fires a nine-star shard burst when vulnerable.',
    shape: 'polygon',
    sides: 9,
  },
  {
    id: 'elite_nullstone',
    name: 'Elite Nullstone Gravity Well',
    color: ELITE_NULLSTONE_COLOR,
    glowColor: ELITE_NULLSTONE_GLOW,
    size: ELITE_NULLSTONE_RADIUS,
    hp: ELITE_NULLSTONE_HP, atk: ELITE_NULLSTONE_ATK, def: ELITE_NULLSTONE_DEF,
    firstWave: 63,
    description: 'An apex void entity that triggers Event Horizon singularity bursts and launches void tendrils from all directions.',
    shape: 'polygon',
    sides: 10,
  },
  {
    id: 'aliven_spark_cluster',
    name: 'Aliven Spark Cluster',
    color: '#7ab4ff',
    glowColor: '#4488ee',
    size: 5,
    hp: 18, atk: 8, def: 0,
    firstWave: 2,
    description: 'A swarm of 8 alivened motes that drift and seek the player. Each spitter fires a slow, dodgeable bullet every 3–5 s. Defeat all particles to clear the group.',
    shape: 'circle',
  },
  {
    id: 'aliven_shard_bloom',
    name: 'Aliven Shard Bloom',
    color: '#44ee88',
    glowColor: '#22bb66',
    size: 6,
    hp: 28, atk: 12, def: 0,
    firstWave: 5,
    description: 'A crystalline swarm of 10 particles that periodically dash toward the player with staggered, randomised timing.',
    shape: 'circle',
  },
  {
    id: 'aliven_pulse_swarm',
    name: 'Aliven Pulse Swarm',
    color: '#f0d060',
    glowColor: '#c8a020',
    size: 6,
    hp: 38, atk: 14, def: 0,
    firstWave: 8,
    description: 'A citrine-hued swarm of 10 pulsers that emit area shockwaves on randomised cooldowns. The pulses deal bonus damage and stack dangerously at close range.',
    shape: 'circle',
  },
  {
    id: 'aliven_ember_ring',
    name: 'Aliven Ember Ring',
    color: '#ff8c3c',
    glowColor: '#dd4400',
    size: 7,
    hp: 50, atk: 14, def: 0,
    firstWave: 12,
    description: 'A sunstone-tinted cluster of 10 ember particles that leave comet trails as they swirl. High contact damage — stay mobile.',
    shape: 'circle',
  },
  {
    id: 'aliven_void_splinters',
    name: 'Aliven Void Splinters',
    color: '#9966bb',
    glowColor: '#6633aa',
    size: 5,
    hp: 65, atk: 16, def: 0,
    firstWave: 18,
    description: 'A void-tinted swarm of 12 splitter particles. Each particle that falls in battle erupts into 2 weaker child fragments — prioritise area weapons.',
    shape: 'circle',
  },
  {
    id: 'aliven_healer_nodes',
    name: 'Aliven Healer Nodes',
    color: '#cc88ee',
    glowColor: '#aa55cc',
    size: 7,
    hp: 80, atk: 14, def: 0,
    firstWave: 22,
    description: 'An amethyst swarm of 9 particles including healer nodes that restore HP to nearby allies every few seconds. Eliminate healers first — they are marked with a faint outer ring.',
    shape: 'circle',
  },
  {
    id: 'aliven_orbit_bloom',
    name: 'Aliven Orbit Bloom',
    color: '#ff5050',
    glowColor: '#cc1111',
    size: 6,
    hp: 95, atk: 18, def: 0,
    firstWave: 28,
    description: 'A ruby-red swarm of 12 orbiter particles that circle a drifting centroid while relentlessly seeking the player. Beautiful and deadly.',
    shape: 'circle',
  },
  {
    id: 'aliven_quartz_ghost',
    name: 'Aliven Quartz Ghost',
    color: '#d8e8f0',
    glowColor: '#aaccee',
    size: 6,
    hp: 22, atk: 10, def: 0,
    firstWave: 4,
    description: 'A pale quartz swarm of 10 particles that periodically phase into an invulnerable ghost state — time your attacks between their flickers.',
    shape: 'circle',
  },
  {
    id: 'aliven_iolite_prism',
    name: 'Aliven Iolite Prism',
    color: '#6464b4',
    glowColor: '#8888cc',
    size: 6,
    hp: 80, atk: 18, def: 0,
    firstWave: 38,
    description: 'A dense iolite cluster of 14 pulser particles that simultaneously detonate area shockwaves — stay mobile or be overwhelmed.',
    shape: 'circle',
  },
  {
    id: 'aliven_fracteryl_storm',
    name: 'Aliven Fracteryl Storm',
    color: '#cc44ff',
    glowColor: '#ee88ff',
    size: 5,
    hp: 120, atk: 22, def: 0,
    firstWave: 65,
    description: 'A fractal cascade of 18 splitter particles that erupts into smaller fragments on death — dealing with one triggers two more.',
    shape: 'circle',
  },
] as const;
